-- Migration: Sync 339 fields and 13 sections from Angular registry (Feb 23, 2026)

INSERT IGNORE INTO `ref_npa_sections` (`id`, `template_id`, `title`, `description`, `order_index`) VALUES
('PC.I', 'STD_NPA_V2', 'Product Specifications (Basic Information)', 'Core product definition, rationale, and business model', 0),
('PC.II', 'STD_NPA_V2', 'Operational & Technology Information', 'Operating model, booking, technical platform, and resiliency', 1),
('PC.III', 'STD_NPA_V2', 'Pricing Model Details', 'Methodology, assumptions, and validation details', 2),
('PC.IV', 'STD_NPA_V2', 'Risk Analysis', 'Market, liquidity, credit, and reputational risk assessments', 3),
('PC.V', 'STD_NPA_V2', 'Data Management', 'Governance, privacy, and reporting requirements', 4),
('PC.VI', 'STD_NPA_V2', 'Other Risk Identification', 'Additional operational risks and mitigants', 5),
('PC.VII', 'STD_NPA_V2', 'Trading Product Assessment', 'Specific assessment for trading instruments', 6),
('APP.1', 'STD_NPA_V2', 'Appendix 1: Entity/Location', 'Booking and sales entity structure', 7),
('APP.2', 'STD_NPA_V2', 'Appendix 2: Intellectual Property', 'MBS and third-party IP considerations', 8),
('APP.3', 'STD_NPA_V2', 'Appendix 3: Financial Crime', 'AML, sanctions, and fraud risk assessment', 9),
('APP.4', 'STD_NPA_V2', 'Appendix 4: Risk Data Aggregation', 'Compliance with RDAR requirements', 10),
('APP.5', 'STD_NPA_V2', 'Appendix 5: Trading Products', 'Additional info for trading instruments', 11),
('APP.6', 'STD_NPA_V2', 'Appendix 6: Third-Party Platforms', 'Risk assessment for hosted communication channels', 12);

INSERT IGNORE INTO `ref_npa_fields` (`id`, `section_id`, `field_key`, `label`, `field_type`, `is_required`, `tooltip`, `order_index`) VALUES
('FLD_BUSINESS_RATIONALE', 'PC.I', 'business_rationale', 'Business Rationale', 'textarea', 1, NULL, 0),
('FLD_PROBLEM_STATEMENT', 'PC.I', 'problem_statement', 'Problem Statement', 'textarea', 0, NULL, 1),
('FLD_VALUE_PROPOSITION', 'PC.I', 'value_proposition', 'Value Proposition', 'textarea', 0, NULL, 2),
('FLD_CUSTOMER_BENEFIT', 'PC.I', 'customer_benefit', 'Benefits to Customers', 'textarea', 0, NULL, 3),
('FLD_BU_BENEFIT', 'PC.I', 'bu_benefit', 'Benefits to BU/SU', 'textarea', 0, NULL, 4),
('FLD_PRODUCT_NAME', 'PC.I', 'product_name', 'Product Name', 'text', 1, NULL, 5),
('FLD_PRODUCT_TYPE', 'PC.I', 'product_type', 'Product Type', 'dropdown', 0, NULL, 6),
('FLD_UNDERLYING_ASSET', 'PC.I', 'underlying_asset', 'Underlying Asset', 'text', 0, NULL, 7),
('FLD_CURRENCY_DENOMINATION', 'PC.I', 'currency_denomination', 'Currency Denomination', 'dropdown', 0, NULL, 8),
('FLD_TENOR', 'PC.I', 'tenor', 'Tenor', 'text', 0, NULL, 9),
('FLD_FUNDING_TYPE', 'PC.I', 'funding_type', 'Funded vs Unfunded', 'dropdown', 0, NULL, 10),
('FLD_REPRICING_INFO', 'PC.I', 'repricing_info', 'Repricing Information', 'textarea', 0, NULL, 11),
('FLD_PRODUCT_ROLE', 'PC.I', 'product_role', 'Role of Proposing Unit', 'dropdown', 0, NULL, 12),
('FLD_PRODUCT_MATURITY', 'PC.I', 'product_maturity', 'Product Maturity', 'dropdown', 0, NULL, 13),
('FLD_PRODUCT_LIFECYCLE', 'PC.I', 'product_lifecycle', 'Product Life Cycle', 'textarea', 0, NULL, 14),
('FLD_PRODUCT_FEATURES', 'PC.I', 'product_features', 'Product Features Summary', 'textarea', 0, NULL, 15),
('FLD_NOTIONAL_AMOUNT', 'PC.I', 'notional_amount', 'Transaction Volume (Notional)', 'currency', 1, NULL, 16),
('FLD_REVENUE_YEAR1', 'PC.I', 'revenue_year1', 'Revenue Year 1 (Gross)', 'currency', 0, NULL, 17),
('FLD_REVENUE_YEAR1_NET', 'PC.I', 'revenue_year1_net', 'Revenue Year 1 (Net of TP)', 'currency', 0, NULL, 18),
('FLD_REVENUE_YEAR2', 'PC.I', 'revenue_year2', 'Revenue Year 2 (Gross)', 'currency', 0, NULL, 19),
('FLD_REVENUE_YEAR2_NET', 'PC.I', 'revenue_year2_net', 'Revenue Year 2 (Net of TP)', 'currency', 0, NULL, 20),
('FLD_REVENUE_YEAR3', 'PC.I', 'revenue_year3', 'Revenue Year 3 (Gross)', 'currency', 0, NULL, 21),
('FLD_REVENUE_YEAR3_NET', 'PC.I', 'revenue_year3_net', 'Revenue Year 3 (Net of TP)', 'currency', 0, NULL, 22),
('FLD_EXPECTED_VOLUME', 'PC.I', 'expected_volume', 'Expected Annual Volume', 'text', 0, NULL, 23),
('FLD_TARGET_ROI', 'PC.I', 'target_roi', 'Target ROI', 'text', 0, NULL, 24),
('FLD_REVENUE_STREAMS', 'PC.I', 'revenue_streams', 'Revenue Streams', 'bullet_list', 0, NULL, 25),
('FLD_GROSS_MARGIN_SPLIT', 'PC.I', 'gross_margin_split', 'Gross Margin Split', 'textarea', 0, NULL, 26),
('FLD_COST_ALLOCATION', 'PC.I', 'cost_allocation', 'Cost Allocation', 'textarea', 0, NULL, 27),
('FLD_SPV_INVOLVED', 'PC.I', 'spv_involved', 'Is SPV/SPE Involved?', 'yesno', 0, NULL, 28),
('FLD_SPV_DETAILS', 'PC.I', 'spv_details', 'SPV Details', 'textarea', 0, NULL, 29),
('FLD_SPV_ARRANGER', 'PC.I', 'spv_arranger', 'SPV Arranger', 'text', 0, NULL, 30),
('FLD_SPV_COUNTRY', 'PC.I', 'spv_country', 'SPV Country of Incorporation', 'text', 0, NULL, 31),
('FLD_CUSTOMER_SEGMENTS', 'PC.I', 'customer_segments', 'Target Customer Segments', 'multiselect', 0, NULL, 32),
('FLD_CUSTOMER_RESTRICTIONS', 'PC.I', 'customer_restrictions', 'Regulatory Restrictions on Customers', 'textarea', 0, NULL, 33),
('FLD_CUSTOMER_SUITABILITY', 'PC.I', 'customer_suitability', 'Customer Suitability Criteria', 'textarea', 0, NULL, 34),
('FLD_CUSTOMER_MIN_TURNOVER', 'PC.I', 'customer_min_turnover', 'Minimum Annual Turnover', 'currency', 0, NULL, 35),
('FLD_CUSTOMER_GEOGRAPHIC', 'PC.I', 'customer_geographic', 'Geographic Scope', 'multiselect', 0, NULL, 36),
('FLD_DISTRIBUTION_CHANNELS', 'PC.I', 'distribution_channels', 'Distribution Channels', 'multiselect', 0, NULL, 37),
('FLD_CHANNEL_RATIONALE', 'PC.I', 'channel_rationale', 'Multi-Entity/Location Rationale', 'textarea', 0, NULL, 38),
('FLD_SALES_SUITABILITY', 'PC.I', 'sales_suitability', 'Sales Suitability', 'textarea', 0, NULL, 39),
('FLD_ONBOARDING_PROCESS', 'PC.I', 'onboarding_process', 'Customer Onboarding Process', 'textarea', 0, NULL, 40),
('FLD_MARKETING_PLAN', 'PC.I', 'marketing_plan', 'Marketing & Communication Plan', 'textarea', 0, NULL, 41),
('FLD_PAC_REFERENCE', 'PC.I', 'pac_reference', 'PAC Reference Number', 'text', 0, NULL, 42),
('FLD_PAC_CONDITIONS', 'PC.I', 'pac_conditions', 'PAC Conditions List', 'bullet_list', 0, NULL, 43),
('FLD_PAC_DATE', 'PC.I', 'pac_date', 'PAC Approval Date', 'date', 0, NULL, 44),
('FLD_EXTERNAL_PARTIES_INVOLVED', 'PC.I', 'external_parties_involved', 'External Parties Involved?', 'yesno', 0, NULL, 45),
('FLD_IP_CONSIDERATIONS', 'PC.I', 'ip_considerations', 'IP Considerations', 'textarea', 0, NULL, 46),
('FLD_EXTERNAL_PARTY_NAMES', 'PC.I', 'external_party_names', 'External Party Names', 'bullet_list', 0, NULL, 47),
('FLD_RASP_REFERENCE', 'PC.I', 'rasp_reference', 'RASP Baseline Reference', 'text', 0, NULL, 48),
('FLD_ESG_DATA_USED', 'PC.I', 'esg_data_used', 'ESG/Sustainable Data Used?', 'yesno', 0, NULL, 49),
('FLD_FRONT_OFFICE_MODEL', 'PC.II', 'front_office_model', 'Front Office Operating Model', 'textarea', 0, NULL, 50),
('FLD_MIDDLE_OFFICE_MODEL', 'PC.II', 'middle_office_model', 'Middle Office Operating Model', 'textarea', 0, NULL, 51),
('FLD_BACK_OFFICE_MODEL', 'PC.II', 'back_office_model', 'Back Office Operating Model', 'textarea', 0, NULL, 52),
('FLD_THIRD_PARTY_OPS', 'PC.II', 'third_party_ops', 'Third Party Operations', 'textarea', 0, NULL, 53),
('FLD_COLLATERAL_MGMT_OPS', 'PC.II', 'collateral_mgmt_ops', 'Collateral Management Requirements', 'textarea', 0, NULL, 54),
('FLD_BOOKING_LEGAL_FORM', 'PC.II', 'booking_legal_form', 'Booking Legal Form', 'text', 0, NULL, 55),
('FLD_BOOKING_FAMILY', 'PC.II', 'booking_family', 'Booking Family', 'text', 0, NULL, 56),
('FLD_BOOKING_TYPOLOGY', 'PC.II', 'booking_typology', 'Booking Typology', 'text', 0, NULL, 57),
('FLD_PORTFOLIO_ALLOCATION', 'PC.II', 'portfolio_allocation', 'Portfolio Allocation', 'text', 0, NULL, 58),
('FLD_CONFIRMATION_PROCESS', 'PC.II', 'confirmation_process', 'Confirmation Process', 'textarea', 0, NULL, 59),
('FLD_RECONCILIATION', 'PC.II', 'reconciliation', 'Reconciliation', 'textarea', 0, NULL, 60),
('FLD_EXCEPTION_HANDLING', 'PC.II', 'exception_handling', 'Exception & Manual Handling', 'textarea', 0, NULL, 61),
('FLD_ACCOUNTING_TREATMENT', 'PC.II', 'accounting_treatment', 'Accounting Treatment', 'textarea', 0, NULL, 62),
('FLD_SETTLEMENT_FLOW', 'PC.II', 'settlement_flow', 'Settlement Flow Description', 'textarea', 0, NULL, 63),
('FLD_NEW_SYSTEM_CHANGES', 'PC.II', 'new_system_changes', 'New System Changes Required?', 'yesno', 0, NULL, 64),
('FLD_BOOKING_SYSTEM', 'PC.II', 'booking_system', 'Booking System', 'dropdown', 0, NULL, 65),
('FLD_TECH_REQUIREMENTS', 'PC.II', 'tech_requirements', 'Technology Requirements', 'textarea', 0, NULL, 66),
('FLD_SYSTEM_INTEGRATION', 'PC.II', 'system_integration', 'System Integration Scope', 'textarea', 0, NULL, 67),
('FLD_VALUATION_MODEL', 'PC.II', 'valuation_model', 'Valuation Model', 'textarea', 0, NULL, 68),
('FLD_FO_SYSTEM_CHANGES', 'PC.II', 'fo_system_changes', 'Front Office System Changes', 'textarea', 0, NULL, 69),
('FLD_SETTLEMENT_METHOD', 'PC.II', 'settlement_method', 'Settlement Method', 'dropdown', 0, NULL, 70),
('FLD_BE_SYSTEM_CHANGES', 'PC.II', 'be_system_changes', 'Back End System Changes', 'textarea', 0, NULL, 71),
('FLD_MANUAL_WORKAROUNDS', 'PC.II', 'manual_workarounds', 'Manual Work-Arounds', 'textarea', 0, NULL, 72),
('FLD_SYSTEM_ENHANCEMENTS', 'PC.II', 'system_enhancements', 'System Enhancements Involved?', 'yesno', 0, NULL, 73),
('FLD_ISS_DEVIATIONS', 'PC.II', 'iss_deviations', 'ISS Policy Deviations', 'textarea', 0, NULL, 74),
('FLD_PENTEST_STATUS', 'PC.II', 'pentest_status', 'Penetration Test Status', 'dropdown', 0, NULL, 75),
('FLD_SECURITY_ASSESSMENT', 'PC.II', 'security_assessment', 'Security Assessment Details', 'textarea', 0, NULL, 76),
('FLD_GRC_ID', 'PC.II', 'grc_id', 'GRC ID (External Party Risk)', 'text', 0, NULL, 77),
('FLD_HSM_REQUIRED', 'PC.II', 'hsm_required', 'HSM Required?', 'yesno', 0, NULL, 78),
('FLD_RTO_TARGET', 'PC.II', 'rto_target', 'Recovery Time Objective (RTO)', 'text', 0, NULL, 79),
('FLD_RPO_TARGET', 'PC.II', 'rpo_target', 'Recovery Point Objective (RPO)', 'text', 0, NULL, 80),
('FLD_DR_TESTING_PLAN', 'PC.II', 'dr_testing_plan', 'DR Testing Plan', 'textarea', 0, NULL, 81),
('FLD_BIA_CONSIDERATIONS', 'PC.II', 'bia_considerations', 'BIA Considerations', 'textarea', 0, NULL, 82),
('FLD_BCP_REQUIREMENTS', 'PC.II', 'bcp_requirements', 'Updated BCP Requirements', 'textarea', 0, NULL, 83),
('FLD_CONTINUITY_MEASURES', 'PC.II', 'continuity_measures', 'Additional Continuity Measures', 'textarea', 0, NULL, 84),
('FLD_PRICING_MODEL_REQUIRED', 'PC.III', 'pricing_model_required', 'Pricing Model Validation Required?', 'yesno', 0, NULL, 85),
('FLD_PRICING_METHODOLOGY', 'PC.III', 'pricing_methodology', 'Pricing Methodology', 'textarea', 0, NULL, 86),
('FLD_ROAE_ANALYSIS', 'PC.III', 'roae_analysis', 'ROAE Analysis', 'textarea', 0, NULL, 87),
('FLD_PRICING_ASSUMPTIONS', 'PC.III', 'pricing_assumptions', 'Pricing Assumptions', 'textarea', 0, NULL, 88),
('FLD_BESPOKE_ADJUSTMENTS', 'PC.III', 'bespoke_adjustments', 'Bespoke Adjustments', 'textarea', 0, NULL, 89),
('FLD_PRICING_MODEL_NAME', 'PC.III', 'pricing_model_name', 'Pricing Model Name', 'text', 0, NULL, 90),
('FLD_MODEL_VALIDATION_DATE', 'PC.III', 'model_validation_date', 'Model Validation Date', 'date', 0, NULL, 91),
('FLD_MODEL_RESTRICTIONS', 'PC.III', 'model_restrictions', 'Model Restrictions', 'textarea', 0, NULL, 92),
('FLD_RISK_DATA_ASSESSMENT_REF', 'PC.III', 'risk_data_assessment_ref', 'Risk Data Assessment Tool Reference', 'text', 0, NULL, 93),
('FLD_SIMM_TREATMENT', 'PC.III', 'simm_treatment', 'SIMM Treatment', 'textarea', 0, NULL, 94),
('FLD_SIMM_SENSITIVITIES', 'PC.III', 'simm_sensitivities', 'SIMM Sensitivities', 'textarea', 0, NULL, 95),
('FLD_LEGAL_OPINION', 'PC.IV', 'legal_opinion', 'Legal Opinion', 'textarea', 0, NULL, 96),
('FLD_LICENSING_REQUIREMENTS', 'PC.IV', 'licensing_requirements', 'Licensing Requirements', 'textarea', 0, NULL, 97),
('FLD_PRIMARY_REGULATION', 'PC.IV', 'primary_regulation', 'Primary Regulation', 'text', 0, NULL, 98),
('FLD_SECONDARY_REGULATIONS', 'PC.IV', 'secondary_regulations', 'Secondary Regulations', 'bullet_list', 0, NULL, 99),
('FLD_REGULATORY_REPORTING', 'PC.IV', 'regulatory_reporting', 'Regulatory Reporting', 'textarea', 0, NULL, 100),
('FLD_CROSS_BORDER_REGULATIONS', 'PC.IV', 'cross_border_regulations', 'Cross-Border Regulatory Considerations', 'textarea', 0, NULL, 101),
('FLD_LEGAL_DOCS_REQUIRED', 'PC.IV', 'legal_docs_required', 'Legal Documentation Required', 'bullet_list', 0, NULL, 102),
('FLD_SANCTIONS_CHECK', 'PC.IV', 'sanctions_check', 'Sanctions Check', 'yesno', 0, NULL, 103),
('FLD_AML_CONSIDERATIONS', 'PC.IV', 'aml_considerations', 'AML Considerations', 'textarea', 0, NULL, 104),
('FLD_TAX_IMPACT', 'PC.IV', 'tax_impact', 'Tax Impact', 'textarea', 0, NULL, 105),
('FLD_ACCOUNTING_BOOK', 'PC.IV', 'accounting_book', 'Trading Book vs Banking Book', 'dropdown', 0, NULL, 106),
('FLD_FAIR_VALUE_TREATMENT', 'PC.IV', 'fair_value_treatment', 'Fair Value Treatment', 'textarea', 0, NULL, 107),
('FLD_ON_OFF_BALANCE', 'PC.IV', 'on_off_balance', 'On/Off Balance Sheet', 'dropdown', 0, NULL, 108),
('FLD_TAX_JURISDICTIONS', 'PC.IV', 'tax_jurisdictions', 'Tax Jurisdictions Analysis', 'textarea', 0, NULL, 109),
('FLD_MARKET_RISK', 'PC.IV', 'market_risk', 'Market Risk Assessment', 'textarea', 1, NULL, 110),
('FLD_RISK_CLASSIFICATION', 'PC.IV', 'risk_classification', 'Risk Classification', 'dropdown', 0, NULL, 111),
('FLD_PRICING_PARAMETERS', 'PC.IV', 'pricing_parameters', 'Relevant Pricing Parameters', 'textarea', 0, NULL, 112),
('FLD_MRF_IR_DELTA', 'PC.IV', 'mrf_ir_delta', 'MRF: IR Delta', 'yesno', 0, NULL, 113),
('FLD_MRF_IR_VEGA', 'PC.IV', 'mrf_ir_vega', 'MRF: IR Vega', 'yesno', 0, NULL, 114),
('FLD_MRF_IR_GAMMA', 'PC.IV', 'mrf_ir_gamma', 'MRF: IR Gamma', 'yesno', 0, NULL, 115),
('FLD_MRF_FX_DELTA', 'PC.IV', 'mrf_fx_delta', 'MRF: FX Delta', 'yesno', 0, NULL, 116),
('FLD_MRF_FX_VEGA', 'PC.IV', 'mrf_fx_vega', 'MRF: FX Vega', 'yesno', 0, NULL, 117),
('FLD_MRF_EQ_DELTA', 'PC.IV', 'mrf_eq_delta', 'MRF: Equity Delta', 'yesno', 0, NULL, 118),
('FLD_MRF_EQ_VEGA', 'PC.IV', 'mrf_eq_vega', 'MRF: Equity Vega', 'yesno', 0, NULL, 119),
('FLD_MRF_COMMODITY', 'PC.IV', 'mrf_commodity', 'MRF: Commodity', 'yesno', 0, NULL, 120),
('FLD_MRF_CREDIT', 'PC.IV', 'mrf_credit', 'MRF: Credit', 'yesno', 0, NULL, 121),
('FLD_MRF_CORRELATION', 'PC.IV', 'mrf_correlation', 'MRF: Correlation', 'yesno', 0, NULL, 122),
('FLD_LIQUIDITY_RISK', 'PC.IV', 'liquidity_risk', 'Funding/Liquidity Risk', 'textarea', 0, NULL, 123),
('FLD_LIQUIDITY_COST', 'PC.IV', 'liquidity_cost', 'Corporate Risk Liquidity Cost', 'textarea', 0, NULL, 124),
('FLD_CONTINGENT_CASHFLOW', 'PC.IV', 'contingent_cashflow', 'Contingent Cash Flow Risk', 'yesno', 0, NULL, 125),
('FLD_CONTINGENT_CASHFLOW_DESC', 'PC.IV', 'contingent_cashflow_desc', 'Contingent Cash Flow Description', 'textarea', 0, NULL, 126),
('FLD_TRADING_BOOK_ASSIGNMENT', 'PC.IV', 'trading_book_assignment', 'Trading Book Assignment Confirmed?', 'yesno', 0, NULL, 127),
('FLD_REGULATORY_CAPITAL', 'PC.IV', 'regulatory_capital', 'Regulatory Capital Requirements', 'textarea', 0, NULL, 128),
('FLD_VAR_CAPTURE', 'PC.IV', 'var_capture', 'VaR Capture', 'textarea', 0, NULL, 129),
('FLD_MODEL_VALIDATION_PROC', 'PC.IV', 'model_validation_proc', 'Model Validation Procedures', 'textarea', 0, NULL, 130),
('FLD_CREDIT_RISK', 'PC.IV', 'credit_risk', 'Credit Risk Assessment', 'textarea', 1, NULL, 131),
('FLD_NEW_LIMIT_TYPES', 'PC.IV', 'new_limit_types', 'New Credit Limit Types Required?', 'yesno', 0, NULL, 132),
('FLD_CREDIT_SUPPORT_REQUIRED', 'PC.IV', 'credit_support_required', 'Credit Support Required?', 'yesno', 0, NULL, 133),
('FLD_COUNTERPARTY_DEFAULT', 'PC.IV', 'counterparty_default', 'Risk Mitigation Measures', 'textarea', 0, NULL, 134),
('FLD_COLLATERAL_FRAMEWORK', 'PC.IV', 'collateral_framework', 'Collateral Framework', 'textarea', 0, NULL, 135),
('FLD_STRESS_TEST_RESULTS', 'PC.IV', 'stress_test_results', 'Stress Test Results', 'textarea', 0, NULL, 136),
('FLD_STRESS_SCENARIOS', 'PC.IV', 'stress_scenarios', 'Stress Scenarios', 'textarea', 0, NULL, 137),
('FLD_EXPOSURE_LIMITS', 'PC.IV', 'exposure_limits', 'Limits to Cover Exposure', 'textarea', 0, NULL, 138),
('FLD_MONITORING_PARTY', 'PC.IV', 'monitoring_party', 'Monitoring Party', 'text', 0, NULL, 139),
('FLD_CUSTODY_RISK', 'PC.IV', 'custody_risk', 'Custody Risk', 'textarea', 0, NULL, 140),
('FLD_COLLATERAL_RISK_RATED', 'PC.IV', 'collateral_risk_rated', 'Collateral Risk-Rated per Core Policy?', 'yesno', 0, NULL, 141),
('FLD_COUNTERPARTY_RATING', 'PC.IV', 'counterparty_rating', 'Counterparty Rating', 'text', 0, NULL, 142),
('FLD_PFE_STANDARDS', 'PC.IV', 'pfe_standards', 'PFE Standards (Standardized Approach)', 'textarea', 0, NULL, 143),
('FLD_EAD_CALCULATION', 'PC.IV', 'ead_calculation', 'EAD & Capital (Internal Model)', 'textarea', 0, NULL, 144),
('FLD_LARGE_EXPOSURE_RULES', 'PC.IV', 'large_exposure_rules', 'Large Exposure Rules', 'textarea', 0, NULL, 145),
('FLD_CONCENTRATION_LIMITS', 'PC.IV', 'concentration_limits', 'Concentration Limits', 'textarea', 0, NULL, 146),
('FLD_CCR_FRAMEWORK', 'PC.IV', 'ccr_framework', 'Counterparty Credit Risk Framework', 'textarea', 0, NULL, 147),
('FLD_REPUTATIONAL_RISK', 'PC.IV', 'reputational_risk', 'Reputational Risk Assessment', 'textarea', 0, NULL, 148),
('FLD_NEGATIVE_IMPACT', 'PC.IV', 'negative_impact', 'Potential Negative Impact?', 'yesno', 0, NULL, 149),
('FLD_ESG_ASSESSMENT', 'PC.IV', 'esg_assessment', 'ESG Assessment', 'textarea', 0, NULL, 150),
('FLD_ESG_CLASSIFICATION', 'PC.IV', 'esg_classification', 'ESG Classification', 'dropdown', 0, NULL, 151),
('FLD_DATA_GOVERNANCE', 'PC.V', 'data_governance', 'Data Governance Framework', 'textarea', 0, NULL, 152),
('FLD_DATA_OWNERSHIP', 'PC.V', 'data_ownership', 'Data Ownership', 'text', 0, NULL, 153),
('FLD_DATA_STEWARDSHIP', 'PC.V', 'data_stewardship', 'Data Stewardship', 'text', 0, NULL, 154),
('FLD_DATA_QUALITY_MONITORING', 'PC.V', 'data_quality_monitoring', 'Data Quality Monitoring', 'textarea', 0, NULL, 155),
('FLD_DATA_PRIVACY', 'PC.V', 'data_privacy', 'Data Privacy Assessment', 'textarea', 0, NULL, 156),
('FLD_DATA_RETENTION', 'PC.V', 'data_retention', 'Data Retention Policy', 'textarea', 0, NULL, 157),
('FLD_GDPR_COMPLIANCE', 'PC.V', 'gdpr_compliance', 'GDPR/Privacy Compliance', 'yesno', 0, NULL, 158),
('FLD_PURE_ASSESSMENT_ID', 'PC.V', 'pure_assessment_id', 'PURE Assessment ID', 'text', 0, NULL, 159),
('FLD_PURE_PURPOSEFUL', 'PC.V', 'pure_purposeful', 'PURE: Purposeful', 'textarea', 0, NULL, 160),
('FLD_PURE_UNSURPRISING', 'PC.V', 'pure_unsurprising', 'PURE: Unsurprising', 'textarea', 0, NULL, 161),
('FLD_PURE_RESPECTFUL', 'PC.V', 'pure_respectful', 'PURE: Respectful', 'textarea', 0, NULL, 162),
('FLD_PURE_EXPLAINABLE', 'PC.V', 'pure_explainable', 'PURE: Explainable', 'textarea', 0, NULL, 163),
('FLD_REPORTING_REQUIREMENTS', 'PC.V', 'reporting_requirements', 'Risk Data Aggregation & Reporting', 'textarea', 0, NULL, 164),
('FLD_AUTOMATED_REPORTING', 'PC.V', 'automated_reporting', 'Automated Regulatory Reporting', 'textarea', 0, NULL, 165),
('FLD_OTHER_RISKS_EXIST', 'PC.VI', 'other_risks_exist', 'Other Risks Not Described in I-V?', 'yesno', 0, NULL, 166),
('FLD_OPERATIONAL_RISK', 'PC.VI', 'operational_risk', 'Operational Risk Assessment', 'textarea', 0, NULL, 167),
('FLD_ADDITIONAL_RISK_MITIGANTS', 'PC.VI', 'additional_risk_mitigants', 'Additional Risk Mitigants', 'bullet_list', 0, NULL, 168),
('FLD_TRADING_PRODUCT', 'PC.VII', 'trading_product', 'Involves Trading Product?', 'yesno', 0, NULL, 169),
('FLD_APPENDIX5_REQUIRED', 'PC.VII', 'appendix5_required', 'Appendix 5 Assessment Required?', 'yesno', 0, NULL, 170),
('FLD_BOOKING_ENTITY', 'APP.1', 'booking_entity', 'Booking Entity', 'text', 1, NULL, 171),
('FLD_SALES_ENTITY', 'APP.1', 'sales_entity', 'Sales / Origination Entity', 'text', 0, NULL, 172),
('FLD_SALES_LOCATION', 'APP.1', 'sales_location', 'Sales / Origination Location', 'text', 0, NULL, 173),
('FLD_BOOKING_LOCATION', 'APP.1', 'booking_location', 'Booking Location', 'text', 0, NULL, 174),
('FLD_RISK_TAKING_ENTITY', 'APP.1', 'risk_taking_entity', 'Risk Taking Entity', 'text', 0, NULL, 175),
('FLD_RISK_TAKING_LOCATION', 'APP.1', 'risk_taking_location', 'Risk Taking Location', 'text', 0, NULL, 176),
('FLD_PROCESSING_ENTITY', 'APP.1', 'processing_entity', 'Processing Entity', 'text', 0, NULL, 177),
('FLD_PROCESSING_LOCATION', 'APP.1', 'processing_location', 'Processing Location', 'text', 0, NULL, 178),
('FLD_COUNTERPARTY', 'APP.1', 'counterparty', 'Counterparty', 'text', 0, NULL, 179),
('FLD_MBS_IP_EXISTS', 'APP.2', 'mbs_ip_exists', 'MBS IP Created/Used?', 'yesno', 0, NULL, 180),
('FLD_MBS_IP_DETAILS', 'APP.2', 'mbs_ip_details', 'MBS IP Details', 'textarea', 0, NULL, 181),
('FLD_THIRD_PARTY_IP_EXISTS', 'APP.2', 'third_party_ip_exists', 'Third Party IP Used?', 'yesno', 0, NULL, 182),
('FLD_THIRD_PARTY_IP_DETAILS', 'APP.2', 'third_party_ip_details', 'Third Party IP Details', 'textarea', 0, NULL, 183),
('FLD_IP_LICENSING', 'APP.2', 'ip_licensing', 'IP Licensing Arrangements', 'textarea', 0, NULL, 184),
('FLD_AML_ASSESSMENT', 'APP.3', 'aml_assessment', 'AML Assessment', 'textarea', 1, NULL, 185),
('FLD_TERRORISM_FINANCING', 'APP.3', 'terrorism_financing', 'Terrorism Financing Risk', 'textarea', 0, NULL, 186),
('FLD_SANCTIONS_ASSESSMENT', 'APP.3', 'sanctions_assessment', 'Sanctions Assessment', 'textarea', 0, NULL, 187),
('FLD_FRAUD_RISK', 'APP.3', 'fraud_risk', 'Fraud Risk Assessment', 'textarea', 0, NULL, 188),
('FLD_BRIBERY_CORRUPTION', 'APP.3', 'bribery_corruption', 'Bribery & Corruption Risk', 'textarea', 0, NULL, 189),
('FLD_FC_RISK_RATING', 'APP.3', 'fc_risk_rating', 'Overall Financial Crime Risk Rating', 'dropdown', 0, NULL, 190),
('FLD_FC_MITIGATION_MEASURES', 'APP.3', 'fc_mitigation_measures', 'FC Mitigation Measures', 'bullet_list', 0, NULL, 191),
('FLD_RDA_COMPLIANCE', 'APP.4', 'rda_compliance', 'RDA Regulatory Compliance', 'textarea', 0, NULL, 192),
('FLD_RDA_DATA_SOURCES', 'APP.4', 'rda_data_sources', 'Risk Data Sources', 'bullet_list', 0, NULL, 193),
('FLD_RDA_AGGREGATION_METHOD', 'APP.4', 'rda_aggregation_method', 'Data Aggregation Methodology', 'textarea', 0, NULL, 194),
('FLD_APP5_REVENUE_SHARING', 'APP.5', 'app5_revenue_sharing', 'Revenue Sharing Model', 'textarea', 0, NULL, 195),
('FLD_APP5_CAPITAL_ALLOCATION', 'APP.5', 'app5_capital_allocation', 'Capital Allocation', 'textarea', 0, NULL, 196),
('FLD_APP5_HEDGE_PURPOSE', 'APP.5', 'app5_hedge_purpose', 'Hedge Purpose?', 'yesno', 0, NULL, 197),
('FLD_APP5_HEDGE_DESCRIPTION', 'APP.5', 'app5_hedge_description', 'Hedge Description', 'textarea', 0, NULL, 198),
('FLD_COLLATERAL_TYPES', 'APP.5', 'collateral_types', 'Collateral Types', 'multiselect', 0, NULL, 199),
('FLD_CUSTODY_ARRANGEMENTS', 'APP.5', 'custody_arrangements', 'Custody Arrangements', 'textarea', 0, NULL, 200),
('FLD_VALUATION_METHOD', 'APP.5', 'valuation_method', 'Valuation Method', 'textarea', 0, NULL, 201),
('FLD_FUNDING_SOURCE', 'APP.5', 'funding_source', 'Funding Source', 'textarea', 0, NULL, 202),
('FLD_BOOKING_SCHEMA', 'APP.5', 'booking_schema', 'Booking Schema', 'textarea', 0, NULL, 203),
('FLD_LIFECYCLE_MANAGEMENT', 'APP.5', 'lifecycle_management', 'Lifecycle Management', 'textarea', 0, NULL, 204),
('FLD_CROSS_PRODUCT_INTEGRATION', 'APP.5', 'cross_product_integration', 'Cross-Product Integration', 'textarea', 0, NULL, 205),
('FLD_APP5_TECH_ARCHITECTURE', 'APP.5', 'app5_tech_architecture', 'Technology Architecture', 'textarea', 0, NULL, 206),
('FLD_APP5_SECURITY_REQ', 'APP.5', 'app5_security_req', 'Security Requirements', 'textarea', 0, NULL, 207),
('FLD_APP5_SCALABILITY', 'APP.5', 'app5_scalability', 'Scalability Requirements', 'textarea', 0, NULL, 208),
('FLD_APP5_COMPLIANCE_FRAMEWORK', 'APP.5', 'app5_compliance_framework', 'Compliance Framework', 'textarea', 0, NULL, 209),
('FLD_APP5_REG_MONITORING', 'APP.5', 'app5_reg_monitoring', 'Regulatory Monitoring', 'textarea', 0, NULL, 210),
('FLD_THIRD_PARTY_PLATFORM', 'APP.6', 'third_party_platform', 'Third-Party Platform Used?', 'yesno', 0, NULL, 211),
('FLD_PLATFORM_NAME', 'APP.6', 'platform_name', 'Platform Name', 'text', 0, NULL, 212),
('FLD_PLATFORM_RISK_ASSESSMENT', 'APP.6', 'platform_risk_assessment', 'Platform Risk Assessment', 'textarea', 0, NULL, 213),
('FLD_INFO_SECURITY_ASSESSMENT', 'APP.6', 'info_security_assessment', 'Information Security Assessment', 'textarea', 0, NULL, 214),
('FLD_DATA_RESIDENCY', 'APP.6', 'data_residency', 'Data Residency Consideration', 'textarea', 0, NULL, 215),
('FLD_PRODUCT_CURRENCY_PAIR', 'PC.I', 'product_currency_pair', 'Currency Pair (if FX)', 'text', 0, NULL, 216),
('FLD_PRODUCT_BENCHMARK', 'PC.I', 'product_benchmark', 'Benchmark / Reference Rate', 'text', 0, NULL, 217),
('FLD_PRODUCT_NOTIONAL_CCY', 'PC.I', 'product_notional_ccy', 'Notional Currency', 'dropdown', 0, NULL, 218),
('FLD_TRANSFER_PRICING', 'PC.I', 'transfer_pricing', 'Transfer Pricing Methodology', 'textarea', 0, NULL, 219),
('FLD_BREAK_EVEN_TIMELINE', 'PC.I', 'break_even_timeline', 'Break-Even Timeline', 'text', 0, NULL, 220),
('FLD_COMPETITIVE_LANDSCAPE', 'PC.I', 'competitive_landscape', 'Competitive Landscape', 'textarea', 0, NULL, 221),
('FLD_MARKET_OPPORTUNITY', 'PC.I', 'market_opportunity', 'Market Opportunity Assessment', 'textarea', 0, NULL, 222),
('FLD_CUSTOMER_ACCREDITATION', 'PC.I', 'customer_accreditation', 'Customer Accreditation Requirements', 'textarea', 0, NULL, 223),
('FLD_KYC_REQUIREMENTS', 'PC.I', 'kyc_requirements', 'KYC/CDD Requirements', 'textarea', 0, NULL, 224),
('FLD_COMPLAINTS_HANDLING', 'PC.I', 'complaints_handling', 'Complaints Handling Process', 'textarea', 0, NULL, 225),
('FLD_TRADE_CAPTURE_SYSTEM', 'PC.II', 'trade_capture_system', 'Trade Capture System', 'text', 0, NULL, 226),
('FLD_RISK_SYSTEM', 'PC.II', 'risk_system', 'Risk Management System', 'text', 0, NULL, 227),
('FLD_REPORTING_SYSTEM', 'PC.II', 'reporting_system', 'Reporting System', 'text', 0, NULL, 228),
('FLD_STP_RATE', 'PC.II', 'stp_rate', 'Expected STP Rate', 'text', 0, NULL, 229),
('FLD_NOSTRO_ACCOUNTS', 'PC.II', 'nostro_accounts', 'Nostro Account Requirements', 'textarea', 0, NULL, 230),
('FLD_MKTDATA_REQUIREMENTS', 'PC.II', 'mktdata_requirements', 'Market Data Requirements', 'textarea', 0, NULL, 231),
('FLD_FVA_ADJUSTMENT', 'PC.III', 'fva_adjustment', 'FVA Adjustment', 'textarea', 0, NULL, 232),
('FLD_XVA_TREATMENT', 'PC.III', 'xva_treatment', 'XVA Treatment', 'textarea', 0, NULL, 233),
('FLD_DAY_COUNT_CONVENTION', 'PC.III', 'day_count_convention', 'Day Count Convention', 'dropdown', 0, NULL, 234),
('FLD_WRONG_WAY_RISK', 'PC.IV', 'wrong_way_risk', 'Wrong-Way Risk', 'textarea', 0, NULL, 235),
('FLD_CVA_DVA_IMPACT', 'PC.IV', 'cva_dva_impact', 'CVA/DVA Impact', 'textarea', 0, NULL, 236),
('FLD_NETTING_AGREEMENTS', 'PC.IV', 'netting_agreements', 'Netting Agreements', 'textarea', 0, NULL, 237),
('FLD_ISDA_MASTER', 'PC.IV', 'isda_master', 'ISDA Master Agreement', 'yesno', 0, NULL, 238),
('FLD_CSA_IN_PLACE', 'PC.IV', 'csa_in_place', 'CSA in Place', 'yesno', 0, NULL, 239),
('FLD_COUNTRY_RISK', 'PC.IV', 'country_risk', 'Country Risk Assessment', 'textarea', 0, NULL, 240),
('FLD_MODEL_RISK', 'PC.IV', 'model_risk', 'Model Risk', 'textarea', 0, NULL, 241),
('FLD_DATA_LINEAGE', 'PC.V', 'data_lineage', 'Data Lineage Documentation', 'textarea', 0, NULL, 242),
('FLD_DATA_CLASSIFICATION', 'PC.V', 'data_classification', 'Data Classification Level', 'dropdown', 0, NULL, 243),
('FLD_HEDGE_ENTITY', 'APP.1', 'hedge_entity', 'Hedge Entity', 'text', 0, NULL, 244),
('FLD_HEDGE_LOCATION', 'APP.1', 'hedge_location', 'Hedge Location', 'text', 0, NULL, 245),
('FLD_CLEARING_ENTITY', 'APP.1', 'clearing_entity', 'Clearing Entity', 'text', 0, NULL, 246),
('FLD_MARGIN_METHODOLOGY', 'APP.5', 'margin_methodology', 'Margin Methodology', 'textarea', 0, NULL, 247),
('FLD_CLOSE_OUT_NETTING', 'APP.5', 'close_out_netting', 'Close-Out Netting', 'textarea', 0, NULL, 248),
('FLD_TRADE_REPORTING', 'APP.5', 'trade_reporting', 'Trade Reporting Requirements', 'textarea', 0, NULL, 249),
('FLD_CLEARING_OBLIGATION', 'APP.5', 'clearing_obligation', 'Clearing Obligation', 'yesno', 0, NULL, 250),
('FLD_CUSTOMER_OBJECTIVES', 'PC.I', 'customer_objectives', 'Customer Objectives & Risk Profile', 'textarea', 0, NULL, 251),
('FLD_CUSTOMER_KEY_RISKS', 'PC.I', 'customer_key_risks', 'Key Risks Faced by Target Customers', 'textarea', 0, NULL, 252),
('FLD_SALES_SURVEILLANCE', 'PC.I', 'sales_surveillance', 'Sales Surveillance Process', 'textarea', 0, NULL, 253),
('FLD_STAFF_TRAINING', 'PC.I', 'staff_training', 'Staff Training Requirements', 'textarea', 0, NULL, 254),
('FLD_OPS_ADEQUACY_CHECKLIST', 'PC.II', 'ops_adequacy_checklist', 'Operational Adequacy Checklist', 'checkbox_group', 0, NULL, 255),
('FLD_OPERATING_ACCOUNT_CONTROLS', 'PC.II', 'operating_account_controls', 'Operating Account Controls', 'textarea', 0, NULL, 256),
('FLD_LIMIT_STRUCTURE', 'PC.II', 'limit_structure', 'Limit Structure', 'textarea', 0, NULL, 257),
('FLD_LIMIT_MONITORING', 'PC.II', 'limit_monitoring', 'Limit Monitoring Process', 'textarea', 0, NULL, 258),
('FLD_MANUAL_FALLBACK', 'PC.II', 'manual_fallback', 'Manual Process Fallback Required?', 'yesno', 0, NULL, 259),
('FLD_MANUAL_FALLBACK_DETAILS', 'PC.II', 'manual_fallback_details', 'Manual Fallback Details', 'textarea', 0, NULL, 260),
('FLD_COLLATERAL_ELIGIBILITY', 'PC.II', 'collateral_eligibility', 'Eligible Collateral Types', 'textarea', 0, NULL, 261),
('FLD_COLLATERAL_HAIRCUTS', 'PC.II', 'collateral_haircuts', 'Collateral Haircuts', 'textarea', 0, NULL, 262),
('FLD_MARGIN_FREQUENCY', 'PC.II', 'margin_frequency', 'Margining Frequency', 'dropdown', 0, NULL, 263),
('FLD_COLLATERAL_DISPUTES', 'PC.II', 'collateral_disputes', 'Collateral Dispute Resolution', 'textarea', 0, NULL, 264),
('FLD_CUSTODY_REQUIRED', 'PC.II', 'custody_required', 'Custody Account Required?', 'yesno', 0, NULL, 265),
('FLD_CUSTODY_DETAILS', 'PC.II', 'custody_details', 'Custody Arrangement Details', 'textarea', 0, NULL, 266),
('FLD_TRADE_REPOSITORY_REPORTING', 'PC.II', 'trade_repository_reporting', 'Trade Repository / ESFR Reporting', 'textarea', 0, NULL, 267),
('FLD_SFEMC_REFERENCES', 'PC.II', 'sfemc_references', 'SFEMC / Code of Conduct References', 'textarea', 0, NULL, 268),
('FLD_BCM_CRITICAL_PROCESSES', 'PC.II', 'bcm_critical_processes', 'Critical Business Processes', 'textarea', 0, NULL, 269),
('FLD_BCM_RECOVERY_STRATEGY', 'PC.II', 'bcm_recovery_strategy', 'Recovery Strategy', 'textarea', 0, NULL, 270),
('FLD_BCM_ALTERNATE_SITE', 'PC.II', 'bcm_alternate_site', 'Alternate Site Arrangements', 'textarea', 0, NULL, 271),
('FLD_BCM_COMMUNICATION_PLAN', 'PC.II', 'bcm_communication_plan', 'Crisis Communication Plan', 'textarea', 0, NULL, 272),
('FLD_BCM_TESTING_FREQUENCY', 'PC.II', 'bcm_testing_frequency', 'BCM Testing Frequency', 'dropdown', 0, NULL, 273),
('FLD_BCM_VENDOR_DEPENDENCIES', 'PC.II', 'bcm_vendor_dependencies', 'Vendor/Third-Party Dependencies', 'textarea', 0, NULL, 274),
('FLD_BCM_STAFF_AWARENESS', 'PC.II', 'bcm_staff_awareness', 'Staff Awareness & Training', 'textarea', 0, NULL, 275),
('FLD_BCM_REGULATORY_COMPLIANCE', 'PC.II', 'bcm_regulatory_compliance', 'BCM Regulatory Compliance', 'textarea', 0, NULL, 276),
('FLD_BCM_INCIDENT_RESPONSE', 'PC.II', 'bcm_incident_response', 'Incident Response Plan', 'textarea', 0, NULL, 277),
('FLD_SIMM_BACKTESTING', 'PC.III', 'simm_backtesting', 'SIMM Backtesting Results', 'textarea', 0, NULL, 278),
('FLD_SERVICE_OUTPUT_FEES', 'PC.IV', 'service_output_fees', 'Service Output Fees', 'textarea', 0, NULL, 279),
('FLD_SERVICE_FEE_STRUCTURE', 'PC.IV', 'service_fee_structure', 'Fee Structure Details', 'textarea', 0, NULL, 280),
('FLD_SERVICE_FEE_ALLOCATION', 'PC.IV', 'service_fee_allocation', 'Fee Allocation Methodology', 'textarea', 0, NULL, 281),
('FLD_REG_MATCHING_IFRS', 'PC.IV', 'reg_matching_ifrs', 'IFRS Regulatory Matching', 'textarea', 0, NULL, 282),
('FLD_REG_MATCHING_MAS', 'PC.IV', 'reg_matching_mas', 'MAS Notice Regulatory Matching', 'textarea', 0, NULL, 283),
('FLD_REG_MATCHING_GST', 'PC.IV', 'reg_matching_gst', 'GST Treatment', 'textarea', 0, NULL, 284),
('FLD_REG_MATCHING_WHT', 'PC.IV', 'reg_matching_wht', 'Withholding Tax Treatment', 'textarea', 0, NULL, 285),
('FLD_FC_CONDUCT_CONSIDERATIONS', 'PC.IV', 'fc_conduct_considerations', 'Conduct Considerations', 'textarea', 0, NULL, 286),
('FLD_FC_MAR_ASSESSMENT', 'PC.IV', 'fc_mar_assessment', 'MAR Assessment', 'textarea', 0, NULL, 287),
('FLD_FC_MAR_SUB_ITEMS', 'PC.IV', 'fc_mar_sub_items', 'MAR Sub-Items (MAS References)', 'bullet_list', 0, NULL, 288),
('FLD_FC_MRA_BOUNDARY_TEST', 'PC.IV', 'fc_mra_boundary_test', 'MRA Boundary Test Required?', 'yesno', 0, NULL, 289),
('FLD_FC_MRA_DETAILS', 'PC.IV', 'fc_mra_details', 'MRA Boundary Test Details', 'textarea', 0, NULL, 290),
('FLD_FLR_LCR_NSFR_METRICS', 'PC.IV', 'flr_lcr_nsfr_metrics', 'LCR/NSFR/EAFL Metrics', 'textarea', 0, NULL, 291),
('FLD_FLR_HQLA_QUALIFICATION', 'PC.IV', 'flr_hqla_qualification', 'HQLA Qualification', 'yesno', 0, NULL, 292),
('FLD_FLR_CASHFLOW_MODELING', 'PC.IV', 'flr_cashflow_modeling', 'Cashflow Modeling', 'textarea', 0, NULL, 293),
('FLD_FLR_LIQUIDITY_FACILITY', 'PC.IV', 'flr_liquidity_facility', 'Liquidity Facility Required?', 'yesno', 0, NULL, 294),
('FLD_FLR_LIMIT_IMPLEMENTATION', 'PC.IV', 'flr_limit_implementation', 'Limit Implementation Plan', 'textarea', 0, NULL, 295),
('FLD_APP5_VALUATION_MODEL', 'APP.5', 'app5_valuation_model', 'Valuation Model (Trading)', 'textarea', 0, NULL, 296),
('FLD_RDA_REPORTING_FREQUENCY', 'PC.V', 'rda_reporting_frequency', 'RDAR Reporting Frequency', 'dropdown', 0, NULL, 297),
('FLD_RDA_DATA_QUALITY', 'APP.4', 'rda_data_quality', 'Data Quality Assessment', 'textarea', 0, NULL, 298),
('FLD_FC_POLICY_FRAMEWORK', 'APP.3', 'fc_policy_framework', 'Financial Crime Policy Framework', 'textarea', 0, NULL, 299),
('FLD_FC_SCREENING_CONTROLS', 'APP.3', 'fc_screening_controls', 'Screening Controls', 'textarea', 0, NULL, 300),
('FLD_FC_TRANSACTION_MONITORING', 'APP.3', 'fc_transaction_monitoring', 'Transaction Monitoring', 'textarea', 0, NULL, 301),
('FLD_FC_SUSPICIOUS_REPORTING', 'APP.3', 'fc_suspicious_reporting', 'Suspicious Transaction Reporting', 'textarea', 0, NULL, 302),
('FLD_FC_RECORD_KEEPING', 'APP.3', 'fc_record_keeping', 'Record Keeping Requirements', 'textarea', 0, NULL, 303),
('FLD_FC_STAFF_TRAINING', 'APP.3', 'fc_staff_training', 'Financial Crime Staff Training', 'textarea', 0, NULL, 304),
('FLD_FC_INDEPENDENT_TESTING', 'APP.3', 'fc_independent_testing', 'Independent Testing Program', 'textarea', 0, NULL, 305),
('FLD_FC_VALIDATION_PROCESS', 'APP.3', 'fc_validation_process', 'Validation Process', 'textarea', 0, NULL, 306),
('FLD_FC_SURVEILLANCE_TOOLS', 'APP.3', 'fc_surveillance_tools', 'Surveillance Tools', 'textarea', 0, NULL, 307),
('FLD_FC_REGULATORY_REPORTING', 'APP.3', 'fc_regulatory_reporting', 'Regulatory Reporting Obligations', 'textarea', 0, NULL, 308),
('FLD_FC_DATA_PRIVACY_COMPLIANCE', 'APP.3', 'fc_data_privacy_compliance', 'Data Privacy Compliance', 'textarea', 0, NULL, 309),
('FLD_FC_DATA_SHARING_AGREEMENTS', 'APP.3', 'fc_data_sharing_agreements', 'Data Sharing Agreements', 'textarea', 0, NULL, 310),
('FLD_TP_USE_CASE_DESCRIPTION', 'APP.6', 'tp_use_case_description', 'Use Case Description', 'textarea', 0, NULL, 311),
('FLD_TP_BUSINESS_JUSTIFICATION', 'APP.6', 'tp_business_justification', 'Business Justification', 'textarea', 0, NULL, 312),
('FLD_TP_RISK_RATING', 'APP.6', 'tp_risk_rating', 'Risk Rating', 'dropdown', 0, NULL, 313),
('FLD_TP_RISK_MITIGANTS', 'APP.6', 'tp_risk_mitigants', 'Risk Mitigants', 'textarea', 0, NULL, 314),
('FLD_TP_DATA_CLASSIFICATION', 'APP.6', 'tp_data_classification', 'Data Classification', 'dropdown', 0, NULL, 315),
('FLD_TP_USER_POPULATION', 'APP.6', 'tp_user_population', 'User Population', 'textarea', 0, NULL, 316),
('FLD_TP_INTEGRATION_SCOPE', 'APP.6', 'tp_integration_scope', 'Integration Scope', 'textarea', 0, NULL, 317),
('FLD_TP_DATA_FLOW', 'APP.6', 'tp_data_flow', 'Data Flow Description', 'textarea', 0, NULL, 318),
('FLD_TP_EXIT_STRATEGY', 'APP.6', 'tp_exit_strategy', 'Exit Strategy', 'textarea', 0, NULL, 319),
('FLD_TP_ENCRYPTION_STANDARDS', 'APP.6', 'tp_encryption_standards', 'Encryption Standards', 'textarea', 0, NULL, 320),
('FLD_TP_ACCESS_CONTROLS', 'APP.6', 'tp_access_controls', 'Access Controls', 'textarea', 0, NULL, 321),
('FLD_TP_AUDIT_LOGGING', 'APP.6', 'tp_audit_logging', 'Audit Logging', 'yesno', 0, NULL, 322),
('FLD_TP_VULNERABILITY_MGMT', 'APP.6', 'tp_vulnerability_mgmt', 'Vulnerability Management', 'textarea', 0, NULL, 323),
('FLD_TP_INCIDENT_RESPONSE', 'APP.6', 'tp_incident_response', 'Incident Response Plan', 'textarea', 0, NULL, 324),
('FLD_TP_CERTIFICATIONS', 'APP.6', 'tp_certifications', 'Security Certifications', 'checkbox_group', 0, NULL, 325),
('FLD_TP_CYBER_ASSESSMENT', 'APP.6', 'tp_cyber_assessment', 'Cybersecurity Assessment', 'textarea', 0, NULL, 326),
('FLD_TP_COMMUNICATION_ARCHIVAL', 'APP.6', 'tp_communication_archival', 'Communication Archival', 'yesno', 0, NULL, 327),
('FLD_TP_RETENTION_POLICY', 'APP.6', 'tp_retention_policy', 'Data Retention Policy', 'textarea', 0, NULL, 328),
('FLD_TP_EDISCOVERY', 'APP.6', 'tp_ediscovery', 'e-Discovery Capability', 'yesno', 0, NULL, 329),
('FLD_TP_DATA_OWNERSHIP', 'APP.6', 'tp_data_ownership', 'Data Ownership', 'textarea', 0, NULL, 330),
('FLD_TP_IP_RIGHTS', 'APP.6', 'tp_ip_rights', 'IP Rights', 'textarea', 0, NULL, 331),
('FLD_TP_PDPA_COMPLIANCE', 'APP.6', 'tp_pdpa_compliance', 'PDPA Compliance', 'textarea', 0, NULL, 332),
('FLD_TP_CROSS_BORDER_TRANSFER', 'APP.6', 'tp_cross_border_transfer', 'Cross-Border Data Transfer', 'textarea', 0, NULL, 333),
('FLD_TP_DATA_DELETION', 'APP.6', 'tp_data_deletion', 'Data Deletion Process', 'textarea', 0, NULL, 334),
('FLD_TP_CONSENT_MANAGEMENT', 'APP.6', 'tp_consent_management', 'Consent Management', 'textarea', 0, NULL, 335),
('FLD_TP_BREACH_NOTIFICATION', 'APP.6', 'tp_breach_notification', 'Breach Notification Process', 'textarea', 0, NULL, 336),
('FLD_TP_DPO_CONTACT', 'APP.6', 'tp_dpo_contact', 'Data Protection Officer Contact', 'text', 0, NULL, 337),
('FLD_TP_PRIVACY_IMPACT', 'APP.6', 'tp_privacy_impact', 'Privacy Impact Assessment', 'textarea', 0, NULL, 338);
