-- ============================================================
-- SEED: NPA-2026-005 Supply Chain Finance — Reverse Factoring
-- Complete NPA Draft — All Sections PC.I through APP.6
-- NPA Full, New Product in Group, MEDIUM risk, Transaction Banking
-- ============================================================
SET FOREIGN_KEY_CHECKS=0;

DELETE FROM `npa_form_data` WHERE `project_id` = 'NPA-2026-005';

INSERT IGNORE INTO `npa_form_data` (`project_id`, `field_key`, `field_value`, `lineage`, `confidence_score`) VALUES

-- ================================================================
-- PC.I: PRODUCT SPECIFICATIONS
-- ================================================================
('NPA-2026-005','product_name','Supply Chain Finance — MBS SCF Reverse Factoring Platform','MANUAL',100.00),
('NPA-2026-005','problem_statement','Large APAC corporates (anchor buyers) want to extend Days Payable Outstanding (DPO) while helping their supplier ecosystems get paid early. MBS currently offers traditional trade finance (letters of credit, bills) but lacks a technology-enabled reverse factoring / supply chain finance (SCF) platform. Loss of transaction banking wallet to banks with dedicated SCF platforms (HSBC, Standard Chartered, BNP Paribas).','MANUAL',100.00),
('NPA-2026-005','value_proposition','MBS SCF Reverse Factoring Platform: anchor buyer-approved supplier invoices discounted by MBS at MBS credit risk (not supplier credit risk). Enables anchor buyers to extend DPO by 30-90 days. Suppliers get paid in T+2. Digital-first platform with API connectivity to buyer ERP systems. Target: USD 3B SCF portfolio within 24 months.','MANUAL',100.00),
('NPA-2026-005','customer_benefit','Anchor Buyer benefits: (1) DPO extension 30-90 days, (2) Supplier ecosystem financial health improvement, (3) Digital API integration with SAP/Oracle ERP, (4) No balance sheet usage (off-balance-sheet treatment possible). Supplier benefits: (1) Early payment T+2 at MBS risk-based rate, (2) Improve working capital, (3) No need for existing bank relationship with MBS.','MANUAL',100.00),
('NPA-2026-005','bu_benefit','Transaction Banking: USD 18M Year 1 net interest income + platform fees. USD 3B portfolio generates ~60bps net margin. Anchor buyer relationships: deepens Transaction Banking wallet share. Cross-sell: FX conversion on supplier payments, trade finance for buyer imports.','MANUAL',100.00),
('NPA-2026-005','product_type','Loans and Financing','AUTO',99.00),
('NPA-2026-005','underlying_asset','Accounts receivable: approved supplier invoices confirmed by anchor buyer. Asset: short-term trade receivables, self-liquidating at invoice due date from anchor buyer payment. Typical invoice tenor: 30-90 days (matched to anchor DPO extension).','MANUAL',100.00),
('NPA-2026-005','currency_denomination','USD (primary), SGD, CNH, INR (multi-currency program). Currency selected per anchor buyer program specification.','MANUAL',100.00),
('NPA-2026-005','notional_amount','3000000000.00','MANUAL',100.00),
('NPA-2026-005','tenor','30-90 days (invoice tenor). Revolving program — continuous invoice upload and discounting. Each individual financing: short-term (self-liquidating). Program: multi-year (typically 3-year anchor buyer agreement).','MANUAL',100.00),
('NPA-2026-005','funding_type','Funded','AUTO',99.00),
('NPA-2026-005','product_role','Principal — MBS purchases the receivable (discounts invoice) and holds credit risk on anchor buyer','AUTO',95.00),
('NPA-2026-005','product_maturity','Short-term (30-90 days per invoice). Program: renewed annually. Revolving structure — MBS credit limit approved per anchor buyer.','MANUAL',100.00),
('NPA-2026-005','product_lifecycle','Platform build (6 months, concurrent with NPA process). Pilot with 3 anchor buyers (Q3 2026). Full launch (Q4 2026). Target: 20 anchor buyers by Q2 2027. 200+ suppliers per anchor buyer on average.','MANUAL',100.00),
('NPA-2026-005','product_features','• Reverse factoring / supplier finance structure\n• Anchor buyer-approved invoices: MBS takes anchor buyer credit risk\n• Digital platform: web portal + ERP API (SAP, Oracle, Workday)\n• Multi-currency: USD, SGD, CNH, INR\n• Competitive pricing: SORA +25-50bps for investment-grade anchor buyers\n• Geographic coverage: Singapore, Hong Kong, India, Indonesia, Taiwan\n• Supplier onboarding: digital KYC, EDD for suppliers from high-risk jurisdictions\n• Self-liquidating: anchor buyer pays MBS on invoice due date (no supplier credit risk)','MANUAL',100.00),
('NPA-2026-005','revenue_year1','18000000.00','MANUAL',100.00),
('NPA-2026-005','revenue_year1_net','10800000.00','MANUAL',100.00),
('NPA-2026-005','revenue_year2','36000000.00','MANUAL',100.00),
('NPA-2026-005','revenue_year2_net','21600000.00','MANUAL',100.00),
('NPA-2026-005','revenue_year3','54000000.00','MANUAL',100.00),
('NPA-2026-005','revenue_year3_net','32400000.00','MANUAL',100.00),
('NPA-2026-005','expected_volume','Year 1: USD 1B SCF portfolio (5 anchor buyers × avg USD 200M program). Year 2: USD 2B (15 buyers). Year 3: USD 3B (25+ buyers). Average utilisation rate: 50-60% of approved limits.','MANUAL',100.00),
('NPA-2026-005','target_roi','ROAE: 12-15% (funded lending — RWA on anchor buyer credit exposure). Capital: 8% RWA on USD 1B portfolio = USD 80M RWA. Net interest margin: 60bps on USD 1B = USD 6M + platform fees USD 12M = USD 18M total.','MANUAL',100.00),
('NPA-2026-005','revenue_streams','• Discounting spread: SORA + 25-50bps (anchor buyer risk-based pricing)\n• Platform fee: USD 50K/year per anchor buyer (20 buyers = USD 1M Year 2)\n• Supplier FX conversion: 15bps on non-USD invoice settlement\n• Transaction fee: 5bps per invoice discounted','MANUAL',100.00),
('NPA-2026-005','gross_margin_split','Transaction Banking: 80% (SCF platform revenue). GFM FX: 20% (FX conversion revenue from multi-currency programs)','MANUAL',100.00),
('NPA-2026-005','cost_allocation','Platform build: USD 3.5M one-time (Demica white-label SCF platform licence + MBS customisation). Ongoing: USD 1.2M/year (Demica SaaS licence USD 600K, ops staff 4 FTE, data costs).','MANUAL',100.00),
('NPA-2026-005','spv_involved','No — MBS Bank Ltd direct balance sheet lending. No SPV or securitisation in scope (future possibility for portfolio >USD 5B).','MANUAL',100.00),
('NPA-2026-005','customer_segments','Anchor buyers: large APAC corporates (investment grade preferred, BBB- minimum). Target sectors: (1) Retail and FMCG (long supplier chains), (2) Automotive (complex supply networks), (3) Electronics (TSMC supply chain), (4) Healthcare, (5) Logistics. MBS Transaction Banking existing relationships prioritised.','MANUAL',100.00),
('NPA-2026-005','customer_restrictions','Anchor buyers: MBS Transaction Banking clients with existing credit facility. Minimum program size: USD 50M. Minimum anchor buyer credit rating: B+ (MBS internal rating equivalent). Suppliers: no minimum size. Suppliers from FATF high-risk jurisdictions: enhanced DD required.','MANUAL',100.00),
('NPA-2026-005','customer_suitability','Anchor buyer: corporates — no consumer protection framework applies. Suppliers: SME to large corporate. Platform access: digital onboarding with KYC. No AI/PI suitability requirements (lending product, not investment product).','MANUAL',100.00),
('NPA-2026-005','customer_geographic','Singapore (anchor buyer primary jurisdiction), Hong Kong, India, Indonesia, Taiwan. Supplier geography: global (MBS funds USD invoices for offshore suppliers; MAS regulations apply to MBS Singapore entity).','MANUAL',100.00),
('NPA-2026-005','distribution_channels','MBS Transaction Banking RM (anchor buyer acquisition). Demica SCF platform portal (buyer ERP integration + supplier self-serve portal). API connectivity: SAP Ariba, Oracle Fusion ERP integrations.','MANUAL',100.00),
('NPA-2026-005','sales_suitability','Corporate lending product — no retail suitability requirements. Anchor buyer: standard MBS corporate credit assessment. Suppliers: digital onboarding with simplified KYC (anchor buyer guarantees invoice authenticity).','MANUAL',100.00),
('NPA-2026-005','onboarding_process','Anchor buyer: standard MBS corporate credit process (3-4 weeks). Supplier: digital onboarding via Demica portal (email invite from anchor buyer, digital KYC, 2-5 business days). API integration: SAP/Oracle connector (4-8 weeks for large ERP integration).','MANUAL',100.00),
('NPA-2026-005','marketing_plan','Anchor buyer outreach: Transaction Banking RM-led. Trade finance thought leadership: MBS SCF white paper Q2 2026. Event: MBS Trade Finance Forum (Q3 2026 launch announcement). Industry: association memberships (BAFT, ICC Trade Finance).','MANUAL',100.00),
('NPA-2026-005','pac_reference','PAC-2026-TXB-012','MANUAL',100.00),
('NPA-2026-005','external_parties_involved','Yes — Demica (platform), SAP and Oracle (ERP connectors)','AUTO',99.00),
('NPA-2026-005','external_party_names','Demica Ltd (SCF platform provider), SAP (ERP integration partner), Oracle (ERP integration partner), Moody''s Analytics (credit risk scoring for supplier assessment), Swift (payment network for cross-border supplier payments)','MANUAL',100.00),
('NPA-2026-005','esg_data_used','No (future: ESG-linked SCF pricing for anchor buyers with ESG KPIs — under development for Year 2)','MANUAL',95.00),
('NPA-2026-005','competitive_landscape','SCF market leaders: HSBC (largest APAC SCF book), Standard Chartered (dedicated SCF platform), BNP Paribas (Novate global). MBS differentiator: (1) Digital-first Demica platform (same as StanChart), (2) Strong APAC anchor buyer relationships in Singapore and Indonesia, (3) Competitive pricing on investment-grade anchor buyers. Gap: no existing SCF platform (clean-slate build catching up to competitors).','ADAPTED',85.00),
('NPA-2026-005','market_opportunity','Global SCF market: USD 2.3T outstanding, growing 15% annually. APAC SCF: USD 600B. Banks'' share: ~40% (USD 240B). MBS target: 1-2% APAC market = USD 3-6B by 2028. Year 3 target: USD 3B portfolio represents 1.25% APAC market.','ADAPTED',82.00),
('NPA-2026-005','break_even_timeline','Month 9 — USD 500M portfolio generates USD 3M net interest + platform fees covering all costs. Platform build cost amortised over 5 years (USD 700K p.a.). Break-even at USD 500M portfolio.','MANUAL',100.00),
('NPA-2026-005','kyc_requirements','Anchor buyer: Full Enhanced DD (MBS corporate credit process). Suppliers: Risk-based KYC via Demica platform (simplified for domestic SG suppliers, enhanced for offshore/high-risk jurisdictions). Supplier AML screening: automated via Demica + Refinitiv World Check integration.','MANUAL',100.00),
('NPA-2026-005','customer_accreditation','No MAS suitability requirements (corporate lending, not investment product). Anchor buyer: MBS credit approved. Suppliers: digital KYC completed.','MANUAL',100.00),
('NPA-2026-005','staff_training','Transaction Banking RMs: SCF product training (8 hours, ICC Supply Chain Finance guidelines). Trade Finance Operations: Demica platform operations training (4 hours). Compliance: SCF-specific AML procedures training (3 hours).','MANUAL',100.00),
('NPA-2026-005','customer_objectives','Anchor buyers: DPO extension (30-90 days), supplier ecosystem health, working capital optimisation, digital ERP integration. Suppliers: early payment (T+2 vs net 60/90 days), working capital improvement, access to MBS-priced financing without individual credit relationship with MBS.','MANUAL',100.00),
('NPA-2026-005','customer_key_risks','Anchor buyer risks: (1) MBS credit exposure concentration if program is single-buyer, (2) Counterparty MBS operational risk if platform fails. Supplier risks: (1) Dependence on anchor buyer program for early payment, (2) Platform connectivity risk if ERP integration fails. MBS risks: (1) Anchor buyer credit risk, (2) Invoice fraud risk, (3) Platform technology dependency.','MANUAL',100.00),
('NPA-2026-005','transfer_pricing','Transaction Banking receives SCF NII plus platform fees. GFM FX receives FX conversion spread. FTP: SCF loans funded via MBS Treasury FTP rate (SORA + 15bps internal). Net spread: SORA + 25-50bps (anchor) - SORA + 15bps (FTP) = 10-35bps net spread per invoice.','MANUAL',100.00),

-- ================================================================
-- PC.II: OPERATIONAL & TECHNOLOGY
-- ================================================================
('NPA-2026-005','front_office_model','Transaction Banking RMs: anchor buyer origination, credit application coordination, program structuring. Demica platform: supplier portal management. Trade Finance Sales: day-to-day supplier onboarding support for large programs.','MANUAL',100.00),
('NPA-2026-005','middle_office_model','Trade Finance Operations (Singapore): invoice verification and discounting approval, limit monitoring, exception handling, daily reconciliation. Demica platform: automated invoice matching and approval routing. MO team: 5 staff for SCF operations (2 new hires budgeted).','MANUAL',100.00),
('NPA-2026-005','back_office_model','MBS trade finance back office: settlement of supplier payments via SWIFT MT103. Collection from anchor buyers at invoice maturity. Reconciliation between Demica platform and MBS internal trade finance system.','MANUAL',100.00),
('NPA-2026-005','third_party_ops','Demica Ltd: SCF platform (white-label SaaS), invoice management, supplier portal, ERP connectors. Refinitiv World Check: supplier AML / sanctions screening (integrated into Demica onboarding). SWIFT: cross-border payment network for supplier FX payments.','MANUAL',100.00),
('NPA-2026-005','booking_system','IBS (MBS internal trade finance system) as booking and limit management system. Demica platform as front-end for invoice management and supplier portal. Dual-system: Demica as origination system, IBS as record system of trade finance bookings.','MANUAL',100.00),
('NPA-2026-005','booking_legal_form','Master Receivables Purchase Agreement (MRPA) with anchor buyer. Per-invoice purchase confirmation (electronic — auto-generated by Demica). Supplier Participation Agreement (between supplier and MBS).','MANUAL',100.00),
('NPA-2026-005','booking_family','Trade Finance / Lending','MANUAL',100.00),
('NPA-2026-005','booking_typology','Trade Finance — Supply Chain Finance — Reverse Factoring','MANUAL',100.00),
('NPA-2026-005','portfolio_allocation','MBS Transaction Banking Loan Book. Short-term trade assets portfolio. Classified as: Trade Finance (self-liquidating, eligible for preferential capital treatment under Basel III Art.162).','MANUAL',100.00),
('NPA-2026-005','settlement_method','Supplier payment: SWIFT MT103 on T+2 from invoice approval. Anchor buyer collection: sweep account debit on invoice due date.','MANUAL',100.00),
('NPA-2026-005','settlement_flow','Invoice submitted by supplier → anchor buyer approves in Demica → MBS credit check vs limit → MBS discounts invoice (SWIFT MT103 to supplier) → Anchor buyer pays MBS on due date (SWIFT MT103 reversal). Auto-reconciliation in IBS.','MANUAL',100.00),
('NPA-2026-005','confirmation_process','Demica: electronic confirmation to supplier (email + portal notification). IBS: internal booking confirmation. Supplier: can track discounted invoices in real-time on Demica portal.','MANUAL',100.00),
('NPA-2026-005','reconciliation','Daily: Demica invoice status vs IBS bookings (automated reconciliation). Anchor buyer payment collection: SWIFT credit confirmation vs IBS maturity. Any unmatched positions >1 day: escalated to Trade Ops supervisor.','MANUAL',100.00),
('NPA-2026-005','exception_handling','Invoice dispute (anchor buyer rejects approved invoice): MBS holds funding until dispute resolved (anchor buyer obligation not to reject without valid reason under MRPA). Anchor buyer payment default: standard MBS credit default management process. Platform outage: manual invoice processing SOP (Trade Ops backup procedures).','MANUAL',100.00),
('NPA-2026-005','accounting_treatment','SCF receivables: on-balance-sheet lending (IFRS 9 — amortised cost). Discount income: recognised over invoice tenor using effective interest rate. Origination fees: amortised over invoice life. No derecognition unless Demica securitisation structure activated (future phase).','MANUAL',100.00),
('NPA-2026-005','new_system_changes','Yes — Demica SCF platform (new) + IBS integration (new interface development). ERP connectors: SAP Ariba integration (new) and Oracle Fusion (new). Estimated build: 6 months (parallel with NPA approval timeline).','MANUAL',100.00),
('NPA-2026-005','tech_requirements','(1) Demica white-label SCF platform (SaaS, USD 600K/year licence), (2) IBS integration: Demica → IBS API (MBS internal build, est. 3 months), (3) SAP Ariba integration (standard Demica connector, 4 weeks activation), (4) Oracle Fusion integration (standard Demica connector, 4 weeks), (5) Refinitiv World Check API integration for supplier screening (Demica built-in), (6) SWIFT integration: automated MT103 generation on invoice approval','MANUAL',100.00),
('NPA-2026-005','system_integration','Demica (invoice management) ↔ IBS (bookings) via REST API. Demica ↔ SAP Ariba (invoice upload). Demica ↔ Oracle Fusion (invoice validation). Demica ↔ Refinitiv World Check (AML screening). IBS ↔ SWIFT (payment messages). IBS ↔ MBS FTP system (interest rate feeds).','MANUAL',100.00),
('NPA-2026-005','valuation_model','Amortised cost (no market valuation required for trade receivables). Interest income: effective interest rate on discounted purchase price. No fair value model — short-term, self-liquidating receivables.','MANUAL',100.00),
('NPA-2026-005','trade_capture_system','IBS (MBS internal trade finance booking system). Demica (origination and invoice management system).','MANUAL',100.00),
('NPA-2026-005','risk_system','MBS CreditWeb (anchor buyer credit exposure monitoring). IBS (position and limit monitoring). Demica (invoice-level exposure tracking). Daily limit utilisation report to Trade Finance Risk.','MANUAL',100.00),
('NPA-2026-005','reporting_system','Daily: IBS SCF portfolio report (outstanding, utilisation, maturity). Monthly: Transaction Banking SCF AUM and NII report to Group CFO. Regulatory: MAS credit exposure reporting (MASB 637). Client: Demica portal shows anchor buyer and supplier real-time positions.','MANUAL',100.00),
('NPA-2026-005','stp_rate','85% STP target: Demica automated invoice approval → IBS booking → SWIFT payment. 15% manual: invoices rejected by anchor buyer, FX conversion for non-USD invoices, new supplier KYC processing.','MANUAL',100.00),
('NPA-2026-005','mktdata_requirements','SORA (MBS FTP calculation — MAS published). Moody''s credit ratings (anchor buyer assessment). FX rates: Bloomberg BGN for CNH, INR supplier payment conversions. All included in existing MBS data licences.','MANUAL',100.00),
('NPA-2026-005','hsm_required','No','AUTO',100.00),
('NPA-2026-005','security_assessment','Demica SOC 2 Type II certified. Penetration test: on Demica platform (MBS-commissioned) completed Q1 2026, result: 0 critical. MBS-Demica API: encrypted (TLS 1.3). Demica: ISO 27001 certified. ISS assessment: APPROVED (MBS ISS-2025-VENDOR-094).','MANUAL',100.00),
('NPA-2026-005','pentest_status','Completed','MANUAL',100.00),
('NPA-2026-005','iss_deviations','No ISS deviations. Demica approved under MBS TPRM framework.','MANUAL',100.00),
('NPA-2026-005','grc_id','DEM-2026-001 (Demica), REF-2025-088 (Refinitiv World Check)','MANUAL',100.00),
('NPA-2026-005','rto_target','4 hours (IBS trade booking system). 24 hours (Demica — supplier portal). Invoice payments: 4-hour override via manual SWIFT process.','MANUAL',100.00),
('NPA-2026-005','rpo_target','15 minutes (IBS — real-time replication to DR). Demica: 4 hours (SaaS provider — Demica BCM).','MANUAL',100.00),
('NPA-2026-005','dr_testing_plan','IBS: existing Trade Finance DR test (semi-annual). Demica: annual platform DR test by Demica (MBS participates). Last IBS DR test: Q4 2025, PASS. Demica: DR test planned Q2 2026 (new platform).','MANUAL',100.00),
('NPA-2026-005','bcp_requirements','IBS outage: manual trade finance booking process (SOP-TF-005). Demica outage: emails/PDF invoices from anchor buyer accepted for up to 48h. SWIFT outage: MBS internal payment system (MBS Treasury) as backup for supplier payments.','MANUAL',100.00),
('NPA-2026-005','bia_considerations','Tier 2 (Important): Trade Finance operations. Anchor buyer debit failure: immediate escalation to RM and credit risk. Platform outage >4h: client communication required. Invoice discounting cannot be delayed >24h for approved invoices (supplier expectation of T+2 payment).','MANUAL',100.00),
('NPA-2026-005','continuity_measures','Demica multi-geography cloud hosting (AWS SG + AWS Sydney DR). IBS: MBS Singapore primary DC + DR site. SWIFT: MBS primary SWIFT bureau + backup bureau. Manual backup for invoice processing embedded in Trade Ops SOP.','MANUAL',100.00),
('NPA-2026-005','limit_structure','Per anchor buyer: approved credit facility (range USD 50M–500M). Single invoice: max USD 10M without Head of Trade Finance approval. Obligor limit: 5% of SCF portfolio max per anchor buyer. Country limit: SCF exposure per country within MBS country credit limit.','MANUAL',100.00),
('NPA-2026-005','limit_monitoring','Real-time: IBS limit monitoring (alerts at 80% utilisation). Daily: Trade Finance Risk limit report. Monthly: concentration analysis per anchor buyer, per sector, per country. Breach: immediate freeze on new invoice discounting + Head of Trade Finance notification.','MANUAL',100.00),
('NPA-2026-005','custody_required','No — receivables are financial assets, not securities. No custody arrangement required.','MANUAL',100.00),

-- ================================================================
-- PC.III: PRICING MODEL
-- ================================================================
('NPA-2026-005','pricing_model_required','No — lending product, not a model-priced instrument. Price = SORA + credit spread (risk-based). No complex model required.','MANUAL',100.00),
('NPA-2026-005','pricing_methodology','All-in rate: SORA (1M compounded in arrears, MAS published) + Credit Spread. Credit spread: 25bps (AAA/AA anchor buyer), 35bps (A), 50bps (BBB). Transaction fee: 5bps per invoice. Platform fee: USD 50K/year. FX: market rate (Bloomberg BGN) + 15bps spread for non-USD invoices.','MANUAL',100.00),
('NPA-2026-005','roae_analysis','Year 1 ROAE: 12-15% (USD 1B portfolio, 60bps net margin, USD 80M RWA). Year 2: 16-18% (USD 2B, USD 160M RWA, growing fees). Year 3: 18-20% (USD 3B, platform fees fully covering overhead). MBS minimum: 15% ROAE. Year 1 below target — approved given strategic importance of SCF franchise build.','MANUAL',100.00),
('NPA-2026-005','pricing_assumptions','USD 1B Year 1 portfolio. Average tenor: 60 days. SORA: 3.2%. Anchor buyer spread: blended 38bps. Net spread after FTP (SORA+15bps): 23bps. Transaction fee: 5bps per invoice. Annual NII: USD 6M + USD 12M platform/transaction fees = USD 18M gross.','MANUAL',100.00),
('NPA-2026-005','bespoke_adjustments','Anchor buyer volume incentive: >USD 200M program — spread compressed by 5bps. Approved by Head of Transaction Banking and GFM FTP committee.','MANUAL',100.00),
('NPA-2026-005','pricing_model_name','MBS SCF Credit Spread Matrix v1.0 (risk-based, approved by RMG)','MANUAL',100.00),
('NPA-2026-005','model_validation_date','2025-12-01','MANUAL',100.00),
('NPA-2026-005','model_restrictions','Spread matrix valid for investment-grade anchor buyers (BBB- and above). Sub-investment grade (BB+): escalate to RMG for bespoke pricing — requires senior credit approval.','MANUAL',100.00),
('NPA-2026-005','simm_treatment','N/A — lending product (receivable purchase). No ISDA SIMM applicable. Capital: Basel III standardised approach for trade finance (short-term self-liquidating: 20% CCF for undrawn, 100% for drawn).','MANUAL',100.00),

-- ================================================================
-- PC.IV: RISK ANALYSIS
-- ================================================================
('NPA-2026-005','risk_classification','MEDIUM','AUTO',95.00),
('NPA-2026-005','market_risk','None — fixed spread lending product. No market risk beyond SORA repricing risk (both asset and FTP rate float to SORA — natural hedge). FX risk: non-USD invoices hedged via SWAP or spot (GFM FX desk manages). Open FX position limit: nil (all FX invoices hedged same day).','MANUAL',100.00),
('NPA-2026-005','mrf_fx_delta','Yes — for CNH and INR invoice FX conversions','AUTO',85.00),
('NPA-2026-005','mrf_commodity','No','AUTO',100.00),
('NPA-2026-005','mrf_credit','No','AUTO',100.00),
('NPA-2026-005','liquidity_risk','Short-term: 30-90 day self-liquidating assets. MBS funds SCF assets via wholesale funding (existing MBS Treasury liquidity management). Stress: if anchor buyers default simultaneously — MBS holds receivables for full tenor. Liquidity stress: 10 largest anchor buyers defaulting = USD 500M for 90 days = manageable within MBS liquidity buffer (>USD 5B).','MANUAL',100.00),
('NPA-2026-005','liquidity_cost','FTP: SORA + 15bps on outstanding SCF portfolio. Included in pricing spread. Daily: matching tenor funding from MBS Treasury. Liquidity coverage: short-term trade assets qualify for preferential LCR treatment (100% runoff rate reduced to 20% for commitment, 0% for drawn — self-liquidating trade).','MANUAL',100.00),
('NPA-2026-005','credit_risk','PRIMARY RISK: Anchor buyer credit risk. MBS purchases receivables with full recourse to anchor buyer. Supplier credit risk: NONE (MBS does not have credit exposure to suppliers — all risk is on anchor buyers). Key credit risk controls: (1) Credit facility per anchor buyer (RMG credit committee approved), (2) Invoice diversification (many small invoices vs single large), (3) Self-liquidating nature (30-90 day term reduces credit exposure vs term loans).','MANUAL',100.00),
('NPA-2026-005','counterparty_rating','Anchor buyer minimum: BBB- (internal MBS shadow rating equivalent). Target anchor buyers: investment grade corporates (40% IG, 60% BB+/BB). Supply chain self-liquidating nature partially mitigates lower-rated anchor buyer risk.','MANUAL',100.00),
('NPA-2026-005','credit_support_required','No — MBS lends against anchor buyer-approved invoices. Self-liquidating structure eliminates need for collateral. MRPA: anchor buyer obligation to pay MBS directly on invoice due date.','MANUAL',100.00),
('NPA-2026-005','collateral_framework','Self-liquidating receivables serve as security. No additional collateral required for investment-grade anchor buyers. For BB-rated buyers: additional cash reserve account (5% of program limit) may be required.','MANUAL',100.00),
('NPA-2026-005','custody_risk','N/A — no physical securities involved. Electronic receivables managed in IBS and Demica.','MANUAL',100.00),
('NPA-2026-005','regulatory_capital','Basel III: SCF receivables qualify as short-term self-liquidating trade facilities: 20% CCF (undrawn) / 100% CCF (drawn). Risk weight: anchor buyer risk weight (typically 50-100% for BBB-rated corporates under SA). Preferential treatment: ICC Trade Register evidence supports 50% RW for investment-grade obligors. Year 1 capital: USD 80M RWA = USD 6.4M capital at 8% CET1.','MANUAL',100.00),
('NPA-2026-005','stress_scenarios','Scenario 1: Single largest anchor buyer default (USD 300M program) — MBS holds USD 300M receivables, recovery via MRPA legal claim. Expected recovery: 80% assuming APAC corporate restructuring process. Net loss: USD 60M (covered by MBS SCF risk reserve allocation). Scenario 2: Sector shock (automotive supply chain) — multiple anchor buyer defaults: USD 600M stress exposure. Mitigant: sector concentration limit (max 30% in any one sector). Scenario 3: Demica platform fraud (fake invoice injection): mitigated by anchor buyer approval requirement.','MANUAL',100.00),
('NPA-2026-005','stress_test_results','Annual credit stress test for SCF portfolio: maximum expected loss at 99% VaR (1Y) = USD 45M on USD 1B portfolio (4.5% expected loss in extreme scenario). Within MBS SCF risk limit of USD 50M unexpected loss buffer. Lower than traditional term lending (self-liquidating nature reduces EL vs term loans by ~40%).','MANUAL',100.00),
('NPA-2026-005','reputational_risk','LOW-MEDIUM — SCF is a standard trade finance product. Main risk: if MBS SCF platform is used to launder proceeds (invoice fraud). Mitigants: anchor buyer approval requirement, Refinitiv World Check for supplier sanctions, Demica audit trail for all invoice transactions.','MANUAL',100.00),
('NPA-2026-005','negative_impact','No','AUTO',100.00),
('NPA-2026-005','esg_assessment','Neutral (baseline). Future: ESG-linked SCF pricing (5bps discount for anchor buyers with certified ESG supplier programs) — under development for Year 2. MSCI ESG data integration planned for ESG-linked SCF program.','MANUAL',90.00),
('NPA-2026-005','esg_classification','Neutral','AUTO',90.00),
('NPA-2026-005','exposure_limits','Per anchor buyer limit: range USD 50M–500M (RMG credit committee approved per buyer). Sector concentration: max 30% of SCF portfolio in any one sector. Country concentration: max 20% of SCF portfolio in any one country. Single invoice: max USD 10M.','MANUAL',100.00),
('NPA-2026-005','monitoring_party','RMG Credit: daily limit utilisation, monthly credit review per anchor buyer. Trade Finance Risk: daily portfolio concentration report. MLR: quarterly AML review of SCF transactions. External: Demica audit trail (accessible by Internal Audit).','MANUAL',100.00),
('NPA-2026-005','legal_opinion','Allen & Gledhill: MRPA is an enforceable receivables purchase agreement in Singapore (true sale analysis confirmed). Supplier Participation Agreement: legally binding under Singapore law. Opinion received 2026-01-15. Cross-border: Baker McKenzie for HK and India legal opinions (India: Macroeconomics Advisor, India RBI NBFC considerations for non-bank suppliers).','MANUAL',100.00),
('NPA-2026-005','licensing_requirements','Singapore: MBS Bank Ltd — existing banking licence covers lending/trade finance. No new MAS licence required. India: MBS India branch (existing RBI foreign bank licence). HK: MBS HK (existing HKMA banking licence). Demica: no separate licence required (technology platform provider).','MANUAL',100.00),
('NPA-2026-005','primary_regulation','MAS Banking Act (lending). MAS Notice 637 (Capital adequacy). MAS Notice 626 (AML). MAS TRM (for Demica cloud deployment). Basel III (SCF capital treatment).','MANUAL',100.00),
('NPA-2026-005','secondary_regulations','ICC Supply Chain Finance Guidelines. BAFT Glossary of trade finance terms (definitional compliance). India: RBI Trade Finance Guidelines. HK: HKMA trade finance supervision guidelines. APAC: UNCITRAL Model Law on Secured Transactions (receivables financing).','MANUAL',95.00),
('NPA-2026-005','regulatory_reporting','MAS: monthly banking statistics (lending outstanding). MAS Notice 628: credit concentrate reporting if single anchor buyer >10% of SCF portfolio. RBI: MBS India branch SCF reporting. Internal: monthly Transaction Banking SCF report to Group CFO.','MANUAL',100.00),
('NPA-2026-005','cross_border_regulations','India MBS branch: RBI approval required for anchor buyer trade facilities. Indonesia: OJK (Financial Services Authority) reporting for Indonesian anchor buyers. HK: HKMA credit supervision. Cross-border supplier payments: MAS and SWIFT compliance. No US regulatory considerations (USD Clearing through MBS New York — standard).','MANUAL',100.00),
('NPA-2026-005','legal_docs_required','• Master Receivables Purchase Agreement (MRPA) — per anchor buyer\n• Supplier Participation Agreement (per supplier)\n• Demica Platform Usage Agreement (MBS-Demica)\n• MBS-Supplier terms of service (digital acceptance onboarding)\n• Cross-border addenda: India, HK, Indonesia specific terms\n• Legal opinions: Allen & Gledhill (SG), Baker McKenzie (HK, India)','MANUAL',100.00),
('NPA-2026-005','sanctions_check','Clear - No Matches','AUTO',100.00),
('NPA-2026-005','aml_considerations','HIGH AML risk awareness — trade finance is a FIFA-identified high-risk area. MBS SCF AML controls: (1) All suppliers screened via Refinitiv World Check (sanctions + PEP), (2) Anchor buyer-approved invoices (reduces risk of fictitious invoices), (3) Invoice amount limits (USD 10M max per invoice), (4) Dual banking requirement: supplier must have a bank account for SWIFT payment. Over/under invoicing risk: managed via anchor buyer confirmation requirement.','MANUAL',100.00),
('NPA-2026-005','tax_impact','SCF income: Singapore corporate tax (17%) on interest income and platform fees. GST: exempt on financial services (interest income). Supplier payments: no WHT on trade payments to suppliers. Stamp duty: not applicable to electronic receivables purchase in Singapore.','ADAPTED',88.00),
('NPA-2026-005','accounting_book','Banking Book','AUTO',99.00),
('NPA-2026-005','fair_value_treatment','SCF receivables: amortised cost (IFRS 9). Annual ECL assessment: Stage 1 (general 12-month ECL) for all performing receivables. Stage 2/3 if anchor buyer credit deterioration. ECL model: PD × LGD × EAD (short-term, low PD given IG anchor buyers).','MANUAL',100.00),
('NPA-2026-005','on_off_balance','On-Balance Sheet — SCF receivables are MBS assets','AUTO',99.00),
('NPA-2026-005','tax_jurisdictions','SG: interest income 17% corporate tax, GST exempt. India: MBS branch — interest income subject to Indian income tax (non-resident branch rules). HK: 16.5% profits tax (HK-domiciled anchor buyers). No US tax nexus.','MANUAL',100.00),
('NPA-2026-005','model_risk','Credit risk model: simple PD × LGD × EAD (no complex model). ECL: model risk low (short tenor, investment-grade obligors). Invoice fraud model risk: anchor buyer approval requirement eliminates >90% of fictitious invoice risk.','MANUAL',90.00),
('NPA-2026-005','country_risk','India: Tier 2 (strong GDP growth, RBI regulatory environment, occasional FX reserve volatility). Indonesia: Tier 2 (investment grade sovereign but EM FX volatility). Singapore, HK: Tier 1. Country concentration limit per country: 20% of SCF portfolio. India sub-limit: 15% (EM risk premium).','MANUAL',90.00),

-- ================================================================
-- PC.V: DATA MANAGEMENT
-- ================================================================
('NPA-2026-005','data_governance','SCF data: IBS (golden source for bookings), Demica (invoice data, golden source for supplier information). Data owner: Head of Transaction Banking. Data steward: Trade Finance Operations Manager.','MANUAL',100.00),
('NPA-2026-005','data_ownership','MBS Bank Ltd: all booking, credit, and payment data. Demica: holds invoice data under MBS licence (not Demica IP). Anchor buyer ERP data: passed through Demica but not stored permanently.','MANUAL',100.00),
('NPA-2026-005','data_stewardship','Trade Finance Operations Manager (booking data). Demica System Admin at MBS (platform data). Compliance Officer (AML/KYC data — Refinitiv World Check outputs).','MANUAL',100.00),
('NPA-2026-005','data_quality_monitoring','Daily: IBS vs Demica reconciliation (automated). Monthly: invoice data completeness audit. Quarterly: anchor buyer limit utilisation accuracy vs credit facility. Annual: Internal Audit data quality review of SCF portfolio.','MANUAL',100.00),
('NPA-2026-005','data_privacy','Anchor buyer commercial data (invoice details, DPO terms): BUSINESS CONFIDENTIAL. Supplier data: CONFIDENTIAL (bank account, KYC details). PDPA: Supplier sole proprietors (natural persons) — personal data under PDPA. Corporate suppliers: no PDPA obligation. Demica: DPA executed confirming PDPA compliance.','MANUAL',100.00),
('NPA-2026-005','data_retention','Invoice data: 7 years (MAS banking records requirement). KYC: 5 years post-relationship end. Demica logs: 7 years. AML records: 5 years (MAS Notice 626). Archived to MBS cold storage after 3 years.','MANUAL',100.00),
('NPA-2026-005','gdpr_compliance','Not applicable. No EU retail customers. EU-domiciled suppliers (if any): GDPR B2B exception for corporate data. Demica: processes no EU personal data for MBS SCF program (APAC-only).','MANUAL',100.00),
('NPA-2026-005','pure_assessment_id','N/A — Corporate lending product. No personal data analytics. No PURE assessment required.','MANUAL',100.00),
('NPA-2026-005','reporting_requirements','MAS: monthly banking statistics. Internal: daily SCF book report, monthly P&L and AUM, quarterly credit concentration report. Client: Demica portal real-time for anchor buyers (invoice approval, utilisation). Supplier: Demica portal real-time (invoice status, payment date).','MANUAL',100.00),
('NPA-2026-005','automated_reporting','Automated: Demica daily invoice status feed to IBS, IBS daily SCF book report to risk systems, SWIFT automated MT103 generation. Manual: MAS credit concentration reporting (for buyers >10% portfolio), RBI India branch reporting.','MANUAL',100.00),
('NPA-2026-005','data_lineage','Supplier invoice → Demica (invoice upload) → Anchor buyer approval (Demica) → MBS credit check (IBS) → MBS discount (SWIFT MT103 to supplier) → Anchor buyer payment → IBS closure. Full audit trail: Demica + IBS + SWIFT logs, 7-year retention.','MANUAL',100.00),
('NPA-2026-005','data_classification','Invoice data: BUSINESS CONFIDENTIAL (supplier pricing vs anchor buyer payment terms commercially sensitive). Supplier KYC: CONFIDENTIAL. Booking data: INTERNAL. Payment data: CONFIDENTIAL.','MANUAL',100.00),

-- ================================================================
-- PC.VI: OTHER RISK IDENTIFICATION
-- ================================================================
('NPA-2026-005','other_risks_exist','Yes','MANUAL',100.00),
('NPA-2026-005','operational_risk','(1) Invoice fraud / over/under invoicing: mitigated by anchor buyer approval and invoice limit (USD 10M). (2) Demica platform failure: 4h RTO, manual backup SOP. (3) Anchor buyer ERP integration failure: email-based invoice submission as fallback. (4) Key person risk: Trade Finance Ops team (3 staff trained on Demica). (5) SWIFT payment failure: MBS Treasury backup payment system.','MANUAL',100.00),
('NPA-2026-005','additional_risk_mitigants','• Demica comprehensive audit trail (all invoice actions logged)\n• Anchor buyer mandatory approval for every invoice discounted\n• USD 10M per-invoice limit (prevents large fraud event)\n• Refinitiv World Check supplier screening (every new supplier onboarded)\n• Annual Internal Audit review of SCF operations and controls\n• Trade finance specialist training for all Demica users','MANUAL',100.00),

-- ================================================================
-- PC.VII: TRADING PRODUCT ASSESSMENT
-- ================================================================
('NPA-2026-005','trading_product','No','AUTO',99.00),
('NPA-2026-005','appendix5_required','No','AUTO',99.00),

-- ================================================================
-- APP.1: ENTITY / LOCATION
-- ================================================================
('NPA-2026-005','booking_entity','MBS Bank Ltd Singapore (primary). MBS Bank India branch (Indian programs). MBS Bank (Hong Kong) Ltd (HK anchor buyer programs).','MANUAL',100.00),
('NPA-2026-005','sales_entity','MBS Bank Ltd Singapore (Transaction Banking RMs). MBS India branch (local anchor buyer origination).','MANUAL',100.00),
('NPA-2026-005','booking_location','Singapore (primary). India, Hong Kong (respective MBS entities for local anchor buyer programs).','MANUAL',100.00),
('NPA-2026-005','sales_location','Singapore, Hong Kong, India, Indonesia, Taiwan','MANUAL',100.00),
('NPA-2026-005','risk_taking_entity','MBS Bank Ltd Singapore (credit risk on anchor buyers). MBS India branch (India anchor buyer programs). MBS HK (HK programs).','MANUAL',100.00),
('NPA-2026-005','risk_taking_location','Singapore (primary), India, Hong Kong','MANUAL',100.00),
('NPA-2026-005','processing_entity','MBS Bank Ltd Singapore (Trade Finance Operations). Demica Ltd (platform — outsourced processing as technology provider).','MANUAL',100.00),
('NPA-2026-005','processing_location','Singapore (MBS Trade Ops). Demica cloud: AWS Singapore (primary).','MANUAL',100.00),
('NPA-2026-005','counterparty','Anchor buyers: large APAC corporates (credit exposure). Suppliers: no credit exposure (MBS pays against anchor buyer obligation). SWIFT: payment counterparty (operational, not credit).','MANUAL',100.00),
('NPA-2026-005','hedge_entity','MBS Bank Ltd Singapore (GFM FX desk — hedges CNH/INR invoice FX exposures for multi-currency programs)','MANUAL',100.00),

-- ================================================================
-- APP.2: INTELLECTUAL PROPERTY
-- ================================================================
('NPA-2026-005','mbs_ip_exists','Yes — MBS SCF Platform brand, MBS customisations to Demica white-label','MANUAL',100.00),
('NPA-2026-005','mbs_ip_details','MBS SCF Platform brand (MBS-branded Demica portal). Custom credit spread matrix (MBS RMG proprietary). MBS API integration with anchor buyer ERP systems (custom connectors built by MBS). Master Receivables Purchase Agreement (MBS Legal template).','MANUAL',100.00),
('NPA-2026-005','third_party_ip_exists','Yes','MANUAL',100.00),
('NPA-2026-005','third_party_ip_details','Demica SCF Platform: SaaS licence (USD 600K/year). MBS retains all client and invoice data (not Demica property). Refinitiv World Check: screening data (licensed). SWIFT: payment network (membership-based access via MBS existing SWIFT membership).','MANUAL',100.00),
('NPA-2026-005','ip_licensing','Demica SaaS: USD 600K/year (includes platform, ERP connectors, support). Refinitiv World Check: included in MBS enterprise licence. SWIFT: existing membership. Custom Demica integrations (MBS-built): MBS owns IP of custom connectors.','MANUAL',100.00),

-- ================================================================
-- APP.3: FINANCIAL CRIME
-- ================================================================
('NPA-2026-005','aml_assessment','HIGH risk awareness — Trade finance is a FATF-identified high-risk area for money laundering. MBS TBML (Trade-Based Money Laundering) controls: (1) Anchor buyer approval requirement for all invoices, (2) Refinitiv World Check screening for all suppliers, (3) Invoice amount limits (USD 10M per invoice), (4) Dual banking requirement (supplier must have a bank account), (5) MBS TBML policy DA-TF-002 applied: over/under invoicing detection, multiple payments checks.','MANUAL',100.00),
('NPA-2026-005','terrorism_financing','MEDIUM risk — trade finance can be used for TF via fictitious invoice financing. Mitigated by: anchor buyer approval (goods/services must be real), Refinitiv World Check TF screening, invoice limit (prevents large single TF transaction).','MANUAL',100.00),
('NPA-2026-005','sanctions_assessment','All suppliers screened against OFAC, UN, EU, MAS sanctions lists at onboarding AND each invoice submission date. Anchro buyers: screened at credit approval. MBS SWIFT payments: Firco Continuity screening on all MT103 messages. Automated hold for any sanctions flag.','MANUAL',100.00),
('NPA-2026-005','fraud_risk','MEDIUM — invoice fraud is the primary fraud vector in SCF. Key risks: (1) Fictitious invoices: mitigated by anchor buyer approval, (2) Duplicate invoice financing: IBS checks for duplicate invoice numbers, (3) Diverted payments: supplier bank account verified at onboarding (cannot be changed without enhanced DD), (4) Insider fraud: dual control for all disbursements >USD 1M.','MANUAL',100.00),
('NPA-2026-005','bribery_corruption','LOW — corporate trade product. Standard MBS anti-bribery policy. RMs: annual anti-bribery training. No government procurement. Demica: anti-bribery clause in vendor contract.','MANUAL',100.00),
('NPA-2026-005','fc_risk_rating','MEDIUM-HIGH (due to trade-based ML risk)','MANUAL',100.00),
('NPA-2026-005','fc_mitigation_measures','• Anchor buyer mandatory approval for every invoice\n• Refinitiv World Check: supplier sanctions and PEP screening (every invoice submission)\n• Invoice amount limit: USD 10M per invoice\n• Dual banking: supplier must have existing bank account\n• MBS TBML Policy DA-TF-002 applied to all SCF transactions\n• Demica audit trail: full log of all invoice lifecycle events\n• Quarterly AML review of SCF portfolio by compliance\n• Annual independent TBML audit by Internal Audit','MANUAL',100.00),
('NPA-2026-005','fc_policy_framework','MBS AML/CFT Policy, MBS TBML Policy DA-TF-002, MAS Notice 626, FATF Guidance on Trade Finance (June 2021), ICC Trade Finance best practice guidelines','MANUAL',100.00),
('NPA-2026-005','fc_screening_controls','Supplier onboarding: Refinitiv World Check (sanctions, PEP, adverse news). Invoice submission: re-screening against updated sanctions lists (daily feed). SWIFT payment: Firco Continuity on all MT103 messages. Anchor buyer: annual AML refresh.','MANUAL',100.00),
('NPA-2026-005','fc_transaction_monitoring','MBS FCRM: rules for SCF — (1) Invoice amounts vs historical norms/industry benchmarks (sudden spike flagged), (2) Multiple invoices from same supplier in same day >USD 1M (enhanced review), (3) New supplier with large first invoice: enhanced review.','MANUAL',100.00),
('NPA-2026-005','fc_suspicious_reporting','MLRO reviews all FCRM alerts within 24 hours. STR filed within 15 days of reasonable grounds. Tipping-off controls enforced (Demica portal: no indication to supplier of STR filing).','MANUAL',100.00),
('NPA-2026-005','fc_record_keeping','All KYC, invoice, payment, and screening records retained 7 years (MAS requirement). Demica logs: 7 years. SWIFT messages: 7 years (SWIFT mandate). Archived to MBS cold storage after 3 years.','MANUAL',100.00),
('NPA-2026-005','fc_staff_training','Trade Finance Ops: MBS TBML training module (3 hours). RMs: SCF AML awareness (2 hours). Compliance: annual TBML update training. New staff: mandatory before Demica platform access.','MANUAL',100.00),
('NPA-2026-005','fc_independent_testing','Annual Internal Audit review of SCF AML controls. Semi-annual compliance review of Demica audit logs for suspicious patterns. External: ICC Trade Finance AML best practice gap assessment (planned Year 1).','MANUAL',100.00),
('NPA-2026-005','fc_surveillance_tools','MBS FCRM (case management), Refinitiv World Check (AML/sanctions screening), Firco Continuity (SWIFT screening), Demica (invoice audit trail). Future: Ayasdi AI-based trade finance anomaly detection (Year 2 roadmap).','MANUAL',100.00),
('NPA-2026-005','fc_regulatory_reporting','MAS: STR via STRO portal. India MBS: FIU-IND suspicious transaction reporting. HK: JFIU (Joint Financial Intelligence Unit) STR for HK transactions. Internal: quarterly TBML risk report to Group MLCO.','MANUAL',100.00),

-- ================================================================
-- APP.4: RISK DATA AGGREGATION
-- ================================================================
('NPA-2026-005','rda_compliance','SCF portfolio integrated into MBS Group risk data aggregation (BCBS 239). IBS as golden source for bookings. Demica invoice data reconciled daily to IBS. Country and sector concentration reported monthly to Group Risk.','MANUAL',95.00),
('NPA-2026-005','rda_data_sources','IBS (trade finance bookings, limits, outstanding), Demica (invoice data, supplier data, audit trail), SWIFT (payment confirmation), Refinitiv World Check (AML screening outputs), SORA (interest rate — MAS published)','MANUAL',100.00),
('NPA-2026-005','rda_aggregation_method','Real-time: IBS limit monitoring. Daily: Demica-IBS reconciliation, SWIFT payment confirmation. Monthly: SCF portfolio MIS report. Quarterly: concentration report (country, sector, anchor buyer). Annual: full portfolio ECL assessment.','MANUAL',100.00),
('NPA-2026-005','rda_data_quality','IBS-Demica daily reconciliation target: zero breaks (>0 breaks resolved same day). Payment confirmation: SWIFT MT103 vs IBS 100% match. Invoice data: Demica completeness check on upload (mandatory fields enforced by platform). Annual Internal Audit confirms data accuracy.','MANUAL',100.00),

-- ================================================================
-- APP.6: THIRD-PARTY PLATFORMS
-- ================================================================
('NPA-2026-005','third_party_platform','Yes','MANUAL',100.00),
('NPA-2026-005','platform_name','Demica SCF Platform (white-label, cloud-hosted)','MANUAL',100.00),
('NPA-2026-005','tp_use_case_description','Demica provides the digital supply chain finance platform for MBS: anchor buyer portal, supplier self-service portal, ERP connectivity (SAP Ariba, Oracle Fusion), invoice management, AML screening integration, and reporting dashboard. Core operational dependency for the MBS SCF product.','MANUAL',100.00),
('NPA-2026-005','tp_business_justification','Building SCF platform in-house: 24+ months, USD 5M+. Demica is the market-leading SCF platform (used by Standard Chartered, ING, UniCredit). MBS would be 3 years behind competitors with in-house build. Demica SaaS: live in 6 months at USD 600K/year.','MANUAL',100.00),
('NPA-2026-005','tp_risk_rating','HIGH (Tier 1 Critical Vendor — platform failure = SCF business failure)','MANUAL',100.00),
('NPA-2026-005','tp_risk_mitigants','(1) Demica 99.9% SLA commitment, (2) Data portability clause (30-day exit with all MBS data), (3) AWS multi-region hosting (SG + Sydney DR), (4) MBS owns all client and invoice data (not Demica), (5) Manual email backup invoice process for platform outage','MANUAL',100.00),
('NPA-2026-005','tp_data_classification','BUSINESS CONFIDENTIAL — invoice and pricing data. Demica processes data as MBS data processor (not Demica''s data). MBS retains full data ownership rights.','MANUAL',100.00),
('NPA-2026-005','tp_integration_scope','Demica ↔ IBS (REST API, daily batch + real-time for invoice status). Demica ↔ SAP Ariba (invoice upload integration). Demica ↔ Oracle Fusion (invoice validation integration). Demica ↔ Refinitiv World Check (onboarding screening — built-in Demica connector).','MANUAL',100.00),
('NPA-2026-005','tp_encryption_standards','AES-256 at rest, TLS 1.3 in transit. AWS KMS key management. Demica: ISO 27001 certified. MBS-Demica API: mutual TLS + API key authentication.','MANUAL',100.00),
('NPA-2026-005','tp_access_controls','Role-based: MBS Trade Ops (admin), anchor buyer users (invoice approval), supplier users (invoice submission). MFA required for all MBS staff. Anchor buyer SSO integration with buyer''s own corporate identity provider.','MANUAL',100.00),
('NPA-2026-005','tp_audit_logging','Yes — full audit trail: all invoice lifecycle events (submission, approval, discounting, payment) logged with timestamp and user ID. Tamper-proof (write-once logs). Stored 7 years per MBS requirements.','MANUAL',100.00),
('NPA-2026-005','tp_certifications','ISO 27001, SOC 2 Type II, PCI DSS Level 1 (for payment data). Annual re-certification.','MANUAL',100.00),
('NPA-2026-005','tp_cyber_assessment','Penetration test by MBS (CrowdStrike): Q1 2026, result: 0 critical, 3 medium (patched by Demica within 30 days). Demica annual independent security audit by KPMG.','MANUAL',100.00),
('NPA-2026-005','tp_pdpa_compliance','Demica Data Processing Agreement executed. Demica: PDPA-compliant processor (personal data of sole proprietor suppliers only). PDPA Article 24 safeguards: data transferred to Demica only for SCF processing. No secondary use.','MANUAL',100.00),
('NPA-2026-005','info_security_assessment','Demica ISS assessment: MBS ISS-2025-VENDOR-094. Result: APPROVED with conditions — annual penetration test, quarterly patching review, immediate incident notification. Next review: Q1 2027.','MANUAL',100.00),
('NPA-2026-005','platform_risk_assessment','Vendor risk: HIGH (Tier 1 Critical). Residual risk after mitigants: MEDIUM. Concentration risk: Demica is sole SCF platform provider — no immediate substitute. Exit protection: data portability clause + 6-month transition period contractual right.','MANUAL',100.00),
('NPA-2026-005','data_residency','AWS Singapore (ap-southeast-1): all MBS SCF data. DR: AWS Sydney (ap-southeast-2) — encrypted replication. India program data: AWS Mumbai (ap-south-1) — MAS TRM cloud data residency compliant. No data stored outside MBS-approved regions.','MANUAL',100.00);

SET FOREIGN_KEY_CHECKS=1;
