-- DCE Account Opening — SA-6 Static Configuration Agent Tables
-- Version: 1.0.0 | Date: 2026-03-08
-- Scope: SA-6 Static Configuration Agent (Node N-5)
-- Depends On:
--   SA-1 tables: dce_ao_case_state, dce_ao_node_checkpoint, dce_ao_event_log
--   SA-3 tables: dce_ao_hitl_review_task (reused for TMO_STATIC_REVIEW tasks)
--   SA-5 tables: dce_ao_credit_decision (SA-6 reads credit decisions; never writes)

USE dce_agent;

-- ============================================
-- Table 1: dce_ao_config_spec
-- Configuration specification for UBIX/SIC/CV systems
-- Built by SA-6 from credit decisions + product reference
-- One record per case per attempt (UNIQUE on case_id + attempt_number)
-- ============================================
CREATE TABLE IF NOT EXISTS dce_ao_config_spec (
    spec_id                     VARCHAR(30) PRIMARY KEY,           -- CSPEC-XXXXXX
    case_id                     VARCHAR(20) NOT NULL,
    attempt_number              INT NOT NULL DEFAULT 1,

    -- UBIX configuration (exchange permissions, entity static data)
    ubix_config                 JSON,                              -- {entity_name, LEI, entity_type, regulatory_flags, product_permissions[], ...}

    -- SIC configuration (commission/billing, account mapping)
    sic_config                  JSON,                              -- {account_mapping, commission_rates{}, credit_limits{}, margin_parameters{}, ...}

    -- CV configuration (credit limits, margin requirements)
    cv_config                   JSON,                              -- {contract_mapping, settlement_account, credit_limit_sgd, pce_limit_sgd, margin_rates{}, ...}

    -- Authorised traders from mandate letter
    authorised_traders          JSON,                              -- [{name, designation, id_number, cqg_perms, idb_perms}]

    -- Status tracking
    status                      ENUM('DRAFT','INSTRUCTION_GENERATED','TMO_EXECUTED','TMO_VALIDATED','TMO_DISCREPANCY_FOUND')
                                DEFAULT 'DRAFT',

    -- Source credit decisions (snapshot)
    credit_outcome              ENUM('APPROVED','APPROVED_WITH_CONDITIONS') NOT NULL,
    approved_dce_limit_sgd      DECIMAL(15,2) NOT NULL,
    approved_dce_pce_limit_sgd  DECIMAL(15,2) NOT NULL,
    confirmed_caa_approach      ENUM('IRB','SA') NOT NULL,

    -- Products being configured
    products_requested          JSON,                              -- ["FUTURES","OPTIONS",...]

    -- Agent metadata
    compiled_by_model           VARCHAR(50),
    kb_chunks_used              JSON,
    compiled_at                 DATETIME DEFAULT NOW(),
    updated_at                  DATETIME DEFAULT NOW() ON UPDATE NOW(),

    FOREIGN KEY (case_id) REFERENCES dce_ao_case_state(case_id),
    UNIQUE KEY idx_case_attempt (case_id, attempt_number),
    INDEX idx_case (case_id),
    INDEX idx_status (status)
);

-- ============================================
-- Table 2: dce_ao_tmo_instruction
-- TMO Static instruction document generated by SA-6 LLM node
-- Structured instruction for TMO Static team to execute in UBIX/SIC/CV
-- One record per config spec (UNIQUE on spec_id)
-- ============================================
CREATE TABLE IF NOT EXISTS dce_ao_tmo_instruction (
    instruction_id              VARCHAR(30) PRIMARY KEY,           -- TINST-XXXXXX
    case_id                     VARCHAR(20) NOT NULL,
    spec_id                     VARCHAR(30) NOT NULL,

    -- Instruction document (LLM-generated structured text)
    instruction_document        JSON,                              -- {ubix_instructions, sic_instructions, cv_instructions, trader_setup, validation_checklist}

    -- Instruction metadata
    instruction_url             VARCHAR(500),                      -- TMO workbench URL
    status                      ENUM('GENERATED','SENT_TO_TMO','TMO_EXECUTING','TMO_COMPLETED','TMO_FAILED')
                                DEFAULT 'GENERATED',

    -- Agent metadata
    generated_by_model          VARCHAR(50),
    generated_at                DATETIME DEFAULT NOW(),

    FOREIGN KEY (case_id) REFERENCES dce_ao_case_state(case_id),
    FOREIGN KEY (spec_id) REFERENCES dce_ao_config_spec(spec_id),
    UNIQUE KEY idx_spec (spec_id),
    INDEX idx_case (case_id),
    INDEX idx_status (status)
);

-- ============================================
-- Table 3: dce_ao_system_validation
-- Post-execution validation results per system (UBIX, SIC, CV)
-- One row per (case_id, system_name) — 3 rows per case
-- Written by sa6_validate_system_config after TMO executes
-- ============================================
CREATE TABLE IF NOT EXISTS dce_ao_system_validation (
    validation_id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    case_id                     VARCHAR(20) NOT NULL,
    spec_id                     VARCHAR(30) NOT NULL,

    -- System being validated
    system_name                 ENUM('UBIX','SIC','CV') NOT NULL,

    -- Validation result
    validation_status           ENUM('PASS','FAIL','PARTIAL') NOT NULL,
    fields_checked              INT DEFAULT 0,
    fields_passed               INT DEFAULT 0,
    fields_failed               INT DEFAULT 0,

    -- Discrepancy details (if any)
    discrepancies               JSON,                              -- [{field, expected, actual, severity}]

    -- Read-back values from system (snapshot for audit)
    configured_values           JSON,                              -- Actual values read from system

    -- Metadata
    validated_at                DATETIME DEFAULT NOW(),

    FOREIGN KEY (case_id) REFERENCES dce_ao_case_state(case_id),
    FOREIGN KEY (spec_id) REFERENCES dce_ao_config_spec(spec_id),
    UNIQUE KEY idx_case_system (case_id, spec_id, system_name),
    INDEX idx_case (case_id),
    INDEX idx_status (validation_status)
);
